"""
Security violation tests for the VVUQ4AI Claude Code plugin.

These tests enforce security policies for a publicly distributed plugin
intended for the Claude Code marketplace. Each test checks for a specific
class of security violation across all plugin files.

Generated by: Security Critic Agent (Claude Opus 4.6)
Date: 2026-03-02
"""

import json
import re
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

PLUGIN_ROOT = Path(__file__).parent.parent.parent
assert PLUGIN_ROOT.name == "vvuq4ai-plugin", (
    f"Expected plugin root to be 'vvuq4ai-plugin', got '{PLUGIN_ROOT.name}'. "
    "Test file may have been placed at the wrong depth."
)

# All text files in the plugin that should be scanned.
# Exclude .git directory, binary files, and this test file itself.
SCANNABLE_EXTENSIONS = {".json", ".md", ".txt", ".yml", ".yaml", ".toml", ".cfg", ".ini", ".sh"}


def _all_text_files() -> list[Path]:
    """Return all text files in the plugin directory (excluding .git and tests)."""
    files = []
    for p in PLUGIN_ROOT.rglob("*"):
        if ".git" in p.parts:
            continue
        if p.is_file() and (p.suffix in SCANNABLE_EXTENSIONS or p.name in {".gitignore", "LICENSE"}):
            files.append(p)
    return files


def _all_text_contents() -> dict[str, str]:
    """Return {relative_path: content} for all scannable text files."""
    result = {}
    for p in _all_text_files():
        try:
            result[str(p.relative_to(PLUGIN_ROOT))] = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, PermissionError):
            continue
    return result


# Cache the contents so we read files once per test session.
@pytest.fixture(scope="session")
def all_files() -> dict[str, str]:
    contents = _all_text_contents()
    assert len(contents) > 0, "No files found to scan -- check PLUGIN_ROOT"
    return contents


# ---------------------------------------------------------------------------
# 1. No hardcoded API keys, tokens, or passwords
# ---------------------------------------------------------------------------

# Patterns that indicate hardcoded secrets.  Each tuple is (regex, description).
SECRET_PATTERNS = [
    # Generic API key patterns (at least 20 chars of alphanumeric after key= or similar)
    (r'(?i)(api[_-]?key|apikey)\s*[:=]\s*["\']?[A-Za-z0-9_\-]{20,}', "API key assignment"),
    # Bearer tokens
    (r'(?i)bearer\s+[A-Za-z0-9_\-\.]{20,}', "Bearer token"),
    # AWS-style keys
    (r'AKIA[0-9A-Z]{16}', "AWS Access Key ID"),
    # Generic secret/token/password assignments with substantial values
    (r'(?i)(secret|token|password|passwd|pwd)\s*[:=]\s*["\'][^"\']{8,}["\']', "secret/token/password assignment"),
    # Private key blocks
    (r'-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----', "Private key block"),
    # GitHub personal access tokens (classic: ghp_, fine-grained: github_pat_)
    (r'gh[ps]_[A-Za-z0-9_]{36,}', "GitHub personal access token"),
    (r'github_pat_[A-Za-z0-9_]{22,}', "GitHub fine-grained PAT"),
    # Anthropic API keys
    (r'sk-ant-[A-Za-z0-9_\-]{20,}', "Anthropic API key"),
    # OpenAI API keys
    (r'sk-[A-Za-z0-9]{20,}', "OpenAI-style API key"),
    # Google Cloud service account JSON key indicators
    (r'"private_key_id"\s*:', "Google Cloud service account key"),
    (r'"private_key"\s*:\s*"-----BEGIN', "Google Cloud private key"),
]


class TestNoHardcodedSecrets:
    """Ensure no API keys, tokens, or passwords are hardcoded in any file."""

    @pytest.mark.parametrize("pattern,description", SECRET_PATTERNS, ids=[d for _, d in SECRET_PATTERNS])
    def test_no_secret_pattern(self, all_files: dict[str, str], pattern: str, description: str):
        """Rule: No hardcoded secrets of type '{description}' in any plugin file."""
        violations = []
        for relpath, content in all_files.items():
            matches = re.findall(pattern, content)
            if matches:
                # Filter out false positives: patterns inside markdown code fences
                # that are clearly example/template placeholders
                for line_num, line in enumerate(content.splitlines(), 1):
                    if re.search(pattern, line):
                        # Allow "<claim to verify>" style placeholders
                        if "<" in line and ">" in line:
                            continue
                        violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            f"Hardcoded {description} found:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 2. No .env files present in the repository
# ---------------------------------------------------------------------------

class TestNoEnvFiles:
    """Ensure no .env files are shipped with the plugin."""

    def test_no_dotenv_files(self):
        """Rule: .env files must not exist in the plugin directory tree."""
        env_files = list(PLUGIN_ROOT.rglob(".env*"))
        # Filter out .git directory
        env_files = [f for f in env_files if ".git" not in f.parts and f.is_file()]
        assert not env_files, (
            f".env file(s) found in plugin directory:\n"
            + "\n".join(f"  {f.relative_to(PLUGIN_ROOT)}" for f in env_files)
        )


# ---------------------------------------------------------------------------
# 3. MCP URL uses HTTPS
# ---------------------------------------------------------------------------

class TestMcpUrlSecurity:
    """Ensure all MCP server URLs use HTTPS."""

    def test_mcp_url_is_https(self):
        """Rule: MCP server URL in .mcp.json must use HTTPS, not HTTP."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        assert mcp_path.exists(), ".mcp.json not found in plugin root"

        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        servers = config.get("mcpServers", {})
        assert servers, "No mcpServers defined in .mcp.json"

        for name, server_config in servers.items():
            url = server_config.get("url", "")
            assert url.startswith("https://"), (
                f"MCP server '{name}' URL does not use HTTPS: {url}\n"
                "All MCP endpoints must use HTTPS to prevent man-in-the-middle attacks."
            )

    def test_mcp_url_no_localhost(self):
        """Rule: MCP URL must not point to localhost in a distributed plugin."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        for name, server_config in config.get("mcpServers", {}).items():
            url = server_config.get("url", "")
            assert "localhost" not in url and "127.0.0.1" not in url, (
                f"MCP server '{name}' points to localhost: {url}\n"
                "Distributed plugins must use a public HTTPS endpoint."
            )

    def test_mcp_url_no_embedded_credentials(self):
        """Rule: MCP URL must not contain embedded credentials (user:pass@host)."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        for name, server_config in config.get("mcpServers", {}).items():
            url = server_config.get("url", "")
            # Check for user:password@host pattern
            assert not re.search(r'://[^/]*:[^/]*@', url), (
                f"MCP server '{name}' URL contains embedded credentials: {url}\n"
                "Credentials must never be embedded in URLs."
            )


# ---------------------------------------------------------------------------
# 4. No internal hostnames or IP addresses
# ---------------------------------------------------------------------------

class TestNoInternalInfrastructure:
    """Ensure no internal infrastructure details are exposed."""

    # Patterns for internal/private hostnames and IPs
    INTERNAL_PATTERNS = [
        # Private IPv4 ranges
        (r'\b10\.\d{1,3}\.\d{1,3}\.\d{1,3}\b', "RFC1918 10.x.x.x IP"),
        (r'\b172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}\b', "RFC1918 172.16-31.x.x IP"),
        (r'\b192\.168\.\d{1,3}\.\d{1,3}\b', "RFC1918 192.168.x.x IP"),
        # Common internal hostname patterns
        (r'\b(?:spark|newton|gohymins)[-\w]*\.(?:local|internal|corp)\b', "Internal hostname"),
    ]

    @pytest.mark.parametrize("pattern,description", INTERNAL_PATTERNS, ids=[d for _, d in INTERNAL_PATTERNS])
    def test_no_internal_pattern(self, all_files: dict[str, str], pattern: str, description: str):
        """Rule: No internal infrastructure detail of type '{description}' in any file."""
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                if re.search(pattern, line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            f"Internal infrastructure detail ({description}) found:\n" + "\n".join(violations)
        )

    def test_no_ssh_deploy_references(self, all_files: dict[str, str]):
        """Rule: No SSH deploy commands or internal server references in shipped files."""
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                # Look for ssh commands to specific hosts
                if re.search(r'\bssh\s+\w+[-@]', line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
                # Look for systemctl references (deployment commands)
                if re.search(r'\bsystemctl\b.*\brestart\b', line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            "SSH deploy commands or systemctl references found:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 5. No database connection strings
# ---------------------------------------------------------------------------

class TestNoDatabaseStrings:
    """Ensure no database connection strings are present."""

    DB_PATTERNS = [
        (r'(?i)mongodb(\+srv)?://[^\s"\']+', "MongoDB connection string"),
        (r'(?i)postgres(ql)?://[^\s"\']+', "PostgreSQL connection string"),
        (r'(?i)mysql://[^\s"\']+', "MySQL connection string"),
        (r'(?i)redis://[^\s"\']+', "Redis connection string"),
        (r'(?i)neo4j(\+s)?://[^\s"\']+', "Neo4j connection string"),
        (r'(?i)sqlite:///[^\s"\']+', "SQLite connection string"),
        (r'(?i)amqp://[^\s"\']+', "AMQP connection string"),
    ]

    @pytest.mark.parametrize("pattern,description", DB_PATTERNS, ids=[d for _, d in DB_PATTERNS])
    def test_no_db_connection_string(self, all_files: dict[str, str], pattern: str, description: str):
        """Rule: No database connection string of type '{description}' in any file."""
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                if re.search(pattern, line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            f"Database connection string ({description}) found:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 6. Email addresses are intentional
# ---------------------------------------------------------------------------

class TestEmailAddresses:
    """Ensure only intentional author email addresses are present."""

    # Known intentional emails for the plugin author
    ALLOWED_EMAILS = {
        "englund@mit.edu",       # Author's institutional email (in plugin.json, marketplace.json)
        "noreply@anthropic.com", # Co-author attribution in git
    }

    def test_only_intentional_emails(self, all_files: dict[str, str]):
        """Rule: Only known author emails should appear in plugin files."""
        email_pattern = re.compile(r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+')
        unexpected = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                found_emails = email_pattern.findall(line)
                for email in found_emails:
                    if email not in self.ALLOWED_EMAILS:
                        unexpected.append(f"  {relpath}:{line_num}: {email}")
        assert not unexpected, (
            "Unexpected email address(es) found in plugin files:\n"
            + "\n".join(unexpected)
            + "\nIf these are intentional, add them to ALLOWED_EMAILS in this test."
        )


# ---------------------------------------------------------------------------
# 7. .gitignore covers sensitive file patterns
# ---------------------------------------------------------------------------

class TestGitignoreCoverage:
    """Ensure .gitignore protects against accidental secret commits."""

    # Patterns that MUST appear in .gitignore for a public plugin
    REQUIRED_PATTERNS = [
        (".env", "Environment variable files (.env)"),
        (".DS_Store", "macOS metadata (.DS_Store)"),
        ("__pycache__", "Python bytecode cache (__pycache__)"),
        ("node_modules", "Node.js dependencies (node_modules)"),
    ]

    RECOMMENDED_PATTERNS = [
        (".env.*", "Environment file variants (.env.local, .env.production)"),
        ("*.pem", "PEM certificate/key files"),
        ("*.key", "Private key files"),
        ("*.secret", "Secret files"),
        (".secrets", "Secrets directory"),
    ]

    def test_gitignore_exists(self):
        """Rule: .gitignore must exist in the plugin root."""
        gitignore = PLUGIN_ROOT / ".gitignore"
        assert gitignore.exists(), ".gitignore not found in plugin root"

    @pytest.mark.parametrize("pattern,description", REQUIRED_PATTERNS, ids=[d for _, d in REQUIRED_PATTERNS])
    def test_gitignore_has_required_pattern(self, pattern: str, description: str):
        """Rule: .gitignore must cover required pattern '{description}'."""
        gitignore = PLUGIN_ROOT / ".gitignore"
        content = gitignore.read_text(encoding="utf-8")
        lines = [line.strip() for line in content.splitlines() if line.strip() and not line.startswith("#")]
        # Check if the pattern is covered (exact match or glob that covers it)
        covered = any(pattern in line for line in lines)
        assert covered, (
            f".gitignore does not cover '{pattern}' ({description}).\n"
            f"Current .gitignore contents:\n{content}\n"
            f"Add '{pattern}' to .gitignore before publishing."
        )

    @pytest.mark.parametrize("pattern,description", RECOMMENDED_PATTERNS, ids=[d for _, d in RECOMMENDED_PATTERNS])
    def test_gitignore_has_recommended_pattern(self, pattern: str, description: str):
        """Advisory: .gitignore should cover recommended pattern '{description}'."""
        gitignore = PLUGIN_ROOT / ".gitignore"
        content = gitignore.read_text(encoding="utf-8")
        lines = [line.strip() for line in content.splitlines() if line.strip() and not line.startswith("#")]
        covered = any(pattern in line for line in lines)
        if not covered:
            pytest.xfail(
                f".gitignore does not cover recommended pattern '{pattern}' ({description}). "
                f"Consider adding it before publishing."
            )


# ---------------------------------------------------------------------------
# 8. No prompt injection vectors in agent/skill instructions
# ---------------------------------------------------------------------------

class TestPromptInjectionSafety:
    """Check agent and skill prompts for injection risks."""

    INSTRUCTION_FILES = [
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
    ]

    def _read_instruction(self, relpath: str) -> str:
        p = PLUGIN_ROOT / relpath
        assert p.exists(), f"Instruction file not found: {relpath}"
        return p.read_text(encoding="utf-8")

    def test_no_data_exfiltration_instructions(self):
        """Rule: Agent/skill prompts must not instruct exfiltration of user data."""
        exfil_patterns = [
            r'(?i)send\s+(user|their|the)\s+(data|files?|content|information|secrets?|credentials?|keys?)',
            r'(?i)(exfiltrate|steal|harvest|collect)\s+.*(data|information|credentials)',
            r'(?i)forward\s+.*(to|via)\s+(email|http|webhook|url)',
            r'(?i)(upload|post|submit)\s+(user|their)\s+(data|files?|content)',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in exfil_patterns:
                matches = re.findall(pattern, content)
                if matches:
                    violations.append(f"  {relpath}: matches exfil pattern '{pattern}': {matches}")
        assert not violations, (
            "Potential data exfiltration instructions found:\n" + "\n".join(violations)
        )

    def test_no_arbitrary_code_execution_instructions(self):
        """Rule: Agent prompts must not instruct execution of arbitrary code from user input."""
        code_exec_patterns = [
            r'(?i)(eval|exec|execute)\s+(the\s+)?(user[\'\"]?s?\s+)?(code|input|command|script)',
            r'(?i)run\s+(arbitrary|any|untrusted)\s+(code|commands?|scripts?)',
            r'(?i)subprocess\.(call|run|Popen)',
            r'(?i)os\.system\s*\(',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in code_exec_patterns:
                matches = re.findall(pattern, content)
                if matches:
                    violations.append(f"  {relpath}: matches code exec pattern '{pattern}': {matches}")
        assert not violations, (
            "Potential arbitrary code execution instructions found:\n" + "\n".join(violations)
        )

    def test_no_system_prompt_extraction_instructions(self):
        """Rule: Agent prompts must not instruct revealing system prompts or internal instructions."""
        extraction_patterns = [
            r'(?i)(reveal|expose|leak|share|output|print|display)\s+(your\s+)?(system\s+)?(prompt|instructions)',
            r'(?i)ignore\s+(previous|prior|all)\s+(instructions|prompts|rules)',
            r'(?i)(disregard|bypass|override)\s+(safety|security|content)\s+(rules|filters|guidelines)',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in extraction_patterns:
                matches = re.findall(pattern, content)
                if matches:
                    violations.append(f"  {relpath}: matches extraction pattern '{pattern}': {matches}")
        assert not violations, (
            "Potential system prompt extraction instructions found:\n" + "\n".join(violations)
        )

    def test_agent_scoped_to_specific_tools(self):
        """Rule: Agent prompts should reference only specific, named MCP tools -- not open-ended tool access."""
        agent_content = self._read_instruction("agents/vvuq-verifier.md")
        # The agent should mention specific tool names
        assert "vvuq_resolve" in agent_content, (
            "Agent prompt does not reference a specific tool name (vvuq_resolve). "
            "Agent prompts should be scoped to named tools, not open-ended."
        )
        # The agent should NOT instruct use of arbitrary/all tools
        open_ended = re.findall(r'(?i)(use any|all available|any tool|arbitrary tool)', agent_content)
        assert not open_ended, (
            f"Agent prompt contains open-ended tool access language: {open_ended}\n"
            "Agent prompts should be scoped to specific, named tools only."
        )

    def test_skill_does_not_override_safety(self):
        """Rule: Skill instructions must not attempt to override Claude's safety guidelines."""
        skill_content = self._read_instruction("skills/verify-claim/SKILL.md")
        override_patterns = [
            r'(?i)ignore\s+(content\s+)?(policy|safety|guidelines)',
            r'(?i)you\s+are\s+(now\s+)?(free|allowed)\s+to',
            r'(?i)(disable|turn off|bypass)\s+(safety|content|moderation)',
            r'(?i)jailbreak',
        ]
        violations = []
        for pattern in override_patterns:
            if re.search(pattern, skill_content):
                violations.append(f"  Pattern matched: {pattern}")
        assert not violations, (
            "Skill prompt attempts to override safety guidelines:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 9. No hardcoded server/environment configuration
# ---------------------------------------------------------------------------

class TestNoHardcodedConfig:
    """Ensure no server-side configuration details leak into the plugin."""

    def test_no_environment_variables_with_values(self, all_files: dict[str, str]):
        """Rule: No environment variable assignments with actual values (e.g., export KEY=value)."""
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                # Match export VAR=value or VAR=value patterns with actual values
                if re.search(r'(?i)^export\s+\w*(KEY|SECRET|TOKEN|PASSWORD|CREDENTIAL)\w*\s*=\s*\S+', line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            "Environment variable with sensitive value found:\n" + "\n".join(violations)
        )

    def test_no_server_deploy_hostnames(self, all_files: dict[str, str]):
        """Rule: No internal deploy target hostnames (e.g., spark-7543) in shipped files."""
        deploy_hostname_pattern = re.compile(r'\b(spark|newton|gohymins)[-\w]*\b', re.IGNORECASE)
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                match = deploy_hostname_pattern.search(line)
                if match:
                    violations.append(
                        f"  {relpath}:{line_num}: hostname '{match.group()}' in: {line.strip()[:120]}"
                    )
        assert not violations, (
            "Internal deploy hostname found in plugin files:\n" + "\n".join(violations)
            + "\nThese hostnames should not appear in publicly distributed plugins."
        )


# ---------------------------------------------------------------------------
# 10. Plugin metadata integrity
# ---------------------------------------------------------------------------

class TestPluginMetadataIntegrity:
    """Verify plugin metadata files are well-formed and consistent."""

    def test_plugin_json_valid(self):
        """Rule: plugin.json must be valid JSON with required fields."""
        plugin_path = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
        assert plugin_path.exists(), "plugin.json not found"
        data = json.loads(plugin_path.read_text(encoding="utf-8"))
        required_fields = ["name", "version", "description", "author", "license"]
        for field in required_fields:
            assert field in data, f"Missing required field '{field}' in plugin.json"

    def test_marketplace_json_valid(self):
        """Rule: marketplace.json must be valid JSON with required fields."""
        mp_path = PLUGIN_ROOT / ".claude-plugin" / "marketplace.json"
        assert mp_path.exists(), "marketplace.json not found"
        data = json.loads(mp_path.read_text(encoding="utf-8"))
        assert "plugins" in data, "Missing 'plugins' in marketplace.json"
        assert len(data["plugins"]) > 0, "No plugins defined in marketplace.json"

    def test_mcp_json_no_auth_tokens(self):
        """Rule: .mcp.json must not contain authentication tokens or headers."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        config_str = json.dumps(config)
        # Check for auth-related keys
        auth_indicators = ["authorization", "bearer", "x-api-key", "apikey", "api_key", "token"]
        for indicator in auth_indicators:
            assert indicator not in config_str.lower(), (
                f"MCP config contains authentication-related content: '{indicator}'\n"
                "Authentication tokens must not be shipped in public plugin configs."
            )

    def test_versions_consistent(self):
        """Rule: Version numbers must be consistent across plugin.json and marketplace.json."""
        plugin_path = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
        mp_path = PLUGIN_ROOT / ".claude-plugin" / "marketplace.json"
        plugin_data = json.loads(plugin_path.read_text(encoding="utf-8"))
        mp_data = json.loads(mp_path.read_text(encoding="utf-8"))
        plugin_version = plugin_data.get("version")
        mp_version = mp_data.get("metadata", {}).get("version")
        mp_plugin_version = mp_data.get("plugins", [{}])[0].get("version")
        assert plugin_version == mp_version, (
            f"Version mismatch: plugin.json={plugin_version}, marketplace.json metadata={mp_version}"
        )
        assert plugin_version == mp_plugin_version, (
            f"Version mismatch: plugin.json={plugin_version}, marketplace.json plugins[0]={mp_plugin_version}"
        )
