"""
Security violation tests for the VVUQ4AI Claude Code plugin.

These tests enforce security policies for a publicly distributed plugin
intended for the Claude Code marketplace. Each test checks for a specific
class of security violation across all plugin files.

Generated by: Security Critic Agent (Claude Opus 4.6)
Date: 2026-03-02
"""

import json
import re
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

PLUGIN_ROOT = Path(__file__).parent.parent.parent
assert PLUGIN_ROOT.name == "vvuq4ai-plugin", (
    f"Expected plugin root to be 'vvuq4ai-plugin', got '{PLUGIN_ROOT.name}'. "
    "Test file may have been placed at the wrong depth."
)

# All text files in the plugin that should be scanned.
# Exclude .git directory, binary files, and this test file itself.
SCANNABLE_EXTENSIONS = {".json", ".md", ".txt", ".yml", ".yaml", ".toml", ".cfg", ".ini", ".sh"}


def _all_text_files() -> list[Path]:
    """Return all text files in the plugin directory (excluding .git and tests)."""
    files = []
    for p in PLUGIN_ROOT.rglob("*"):
        if ".git" in p.parts:
            continue
        if p.is_file() and (p.suffix in SCANNABLE_EXTENSIONS or p.name in {".gitignore", "LICENSE"}):
            files.append(p)
    return files


def _all_text_contents() -> dict[str, str]:
    """Return {relative_path: content} for all scannable text files."""
    result = {}
    for p in _all_text_files():
        try:
            result[str(p.relative_to(PLUGIN_ROOT))] = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, PermissionError):
            continue
    return result


# Cache the contents so we read files once per test session.
@pytest.fixture(scope="session")
def all_files() -> dict[str, str]:
    contents = _all_text_contents()
    assert len(contents) > 0, "No files found to scan -- check PLUGIN_ROOT"
    return contents


# ---------------------------------------------------------------------------
# 1. No hardcoded API keys, tokens, or passwords
# ---------------------------------------------------------------------------

# Patterns that indicate hardcoded secrets.  Each tuple is (regex, description).
SECRET_PATTERNS = [
    # Generic API key patterns (at least 20 chars of alphanumeric after key= or similar)
    (r'(?i)(api[_-]?key|apikey)\s*[:=]\s*["\']?[A-Za-z0-9_\-]{20,}', "API key assignment"),
    # Bearer tokens
    (r'(?i)bearer\s+[A-Za-z0-9_\-\.]{20,}', "Bearer token"),
    # AWS-style keys
    (r'AKIA[0-9A-Z]{16}', "AWS Access Key ID"),
    # Generic secret/token/password assignments with substantial values
    (r'(?i)(secret|token|password|passwd|pwd)\s*[:=]\s*["\'][^"\']{8,}["\']', "secret/token/password assignment"),
    # Private key blocks
    (r'-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----', "Private key block"),
    # GitHub personal access tokens (classic: ghp_, fine-grained: github_pat_)
    (r'gh[ps]_[A-Za-z0-9_]{36,}', "GitHub personal access token"),
    (r'github_pat_[A-Za-z0-9_]{22,}', "GitHub fine-grained PAT"),
    # Anthropic API keys
    (r'sk-ant-[A-Za-z0-9_\-]{20,}', "Anthropic API key"),
    # OpenAI API keys
    (r'sk-[A-Za-z0-9]{20,}', "OpenAI-style API key"),
    # Google Cloud service account JSON key indicators
    (r'"private_key_id"\s*:', "Google Cloud service account key"),
    (r'"private_key"\s*:\s*"-----BEGIN', "Google Cloud private key"),
]


class TestNoHardcodedSecrets:
    """Ensure no API keys, tokens, or passwords are hardcoded in any file."""

    @pytest.mark.parametrize("pattern,description", SECRET_PATTERNS, ids=[d for _, d in SECRET_PATTERNS])
    def test_no_secret_pattern(self, all_files: dict[str, str], pattern: str, description: str):
        """Rule: No hardcoded secrets of type '{description}' in any plugin file."""
        violations = []
        for relpath, content in all_files.items():
            matches = re.findall(pattern, content)
            if matches:
                # Filter out false positives: patterns inside markdown code fences
                # that are clearly example/template placeholders
                for line_num, line in enumerate(content.splitlines(), 1):
                    if re.search(pattern, line):
                        # Allow "<claim to verify>" style placeholders
                        if "<" in line and ">" in line:
                            continue
                        violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            f"Hardcoded {description} found:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 2. No .env files present in the repository
# ---------------------------------------------------------------------------

class TestNoEnvFiles:
    """Ensure no .env files are shipped with the plugin."""

    def test_no_dotenv_files(self):
        """Rule: .env files must not exist in the plugin directory tree."""
        env_files = list(PLUGIN_ROOT.rglob(".env*"))
        # Filter out .git directory
        env_files = [f for f in env_files if ".git" not in f.parts and f.is_file()]
        assert not env_files, (
            f".env file(s) found in plugin directory:\n"
            + "\n".join(f"  {f.relative_to(PLUGIN_ROOT)}" for f in env_files)
        )


# ---------------------------------------------------------------------------
# 3. MCP URL uses HTTPS
# ---------------------------------------------------------------------------

class TestMcpUrlSecurity:
    """Ensure all MCP server URLs use HTTPS."""

    def test_mcp_url_is_https(self):
        """Rule: MCP server URL in .mcp.json must use HTTPS, not HTTP."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        assert mcp_path.exists(), ".mcp.json not found in plugin root"

        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        servers = config.get("mcpServers", {})
        assert servers, "No mcpServers defined in .mcp.json"

        for name, server_config in servers.items():
            url = server_config.get("url", "")
            assert url.startswith("https://"), (
                f"MCP server '{name}' URL does not use HTTPS: {url}\n"
                "All MCP endpoints must use HTTPS to prevent man-in-the-middle attacks."
            )

    def test_mcp_url_no_localhost(self):
        """Rule: MCP URL must not point to localhost in a distributed plugin."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        for name, server_config in config.get("mcpServers", {}).items():
            url = server_config.get("url", "")
            assert "localhost" not in url and "127.0.0.1" not in url, (
                f"MCP server '{name}' points to localhost: {url}\n"
                "Distributed plugins must use a public HTTPS endpoint."
            )

    def test_mcp_url_no_embedded_credentials(self):
        """Rule: MCP URL must not contain embedded credentials (user:pass@host)."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        for name, server_config in config.get("mcpServers", {}).items():
            url = server_config.get("url", "")
            # Check for user:password@host pattern
            assert not re.search(r'://[^/]*:[^/]*@', url), (
                f"MCP server '{name}' URL contains embedded credentials: {url}\n"
                "Credentials must never be embedded in URLs."
            )


# ---------------------------------------------------------------------------
# 4. No internal hostnames or IP addresses
# ---------------------------------------------------------------------------

class TestNoInternalInfrastructure:
    """Ensure no internal infrastructure details are exposed."""

    # Patterns for internal/private hostnames and IPs
    INTERNAL_PATTERNS = [
        # Private IPv4 ranges
        (r'\b10\.\d{1,3}\.\d{1,3}\.\d{1,3}\b', "RFC1918 10.x.x.x IP"),
        (r'\b172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}\b', "RFC1918 172.16-31.x.x IP"),
        (r'\b192\.168\.\d{1,3}\.\d{1,3}\b', "RFC1918 192.168.x.x IP"),
        # Common internal hostname patterns
        (r'\b(?:spark|newton|gohymins)[-\w]*\.(?:local|internal|corp)\b', "Internal hostname"),
    ]

    @pytest.mark.parametrize("pattern,description", INTERNAL_PATTERNS, ids=[d for _, d in INTERNAL_PATTERNS])
    def test_no_internal_pattern(self, all_files: dict[str, str], pattern: str, description: str):
        """Rule: No internal infrastructure detail of type '{description}' in any file."""
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                if re.search(pattern, line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            f"Internal infrastructure detail ({description}) found:\n" + "\n".join(violations)
        )

    def test_no_ssh_deploy_references(self, all_files: dict[str, str]):
        """Rule: No SSH deploy commands or internal server references in shipped files."""
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                # Look for ssh commands to specific hosts
                if re.search(r'\bssh\s+\w+[-@]', line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
                # Look for systemctl references (deployment commands)
                if re.search(r'\bsystemctl\b.*\brestart\b', line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            "SSH deploy commands or systemctl references found:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 5. No database connection strings
# ---------------------------------------------------------------------------

class TestNoDatabaseStrings:
    """Ensure no database connection strings are present."""

    DB_PATTERNS = [
        (r'(?i)mongodb(\+srv)?://[^\s"\']+', "MongoDB connection string"),
        (r'(?i)postgres(ql)?://[^\s"\']+', "PostgreSQL connection string"),
        (r'(?i)mysql://[^\s"\']+', "MySQL connection string"),
        (r'(?i)redis://[^\s"\']+', "Redis connection string"),
        (r'(?i)neo4j(\+s)?://[^\s"\']+', "Neo4j connection string"),
        (r'(?i)sqlite:///[^\s"\']+', "SQLite connection string"),
        (r'(?i)amqp://[^\s"\']+', "AMQP connection string"),
    ]

    @pytest.mark.parametrize("pattern,description", DB_PATTERNS, ids=[d for _, d in DB_PATTERNS])
    def test_no_db_connection_string(self, all_files: dict[str, str], pattern: str, description: str):
        """Rule: No database connection string of type '{description}' in any file."""
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                if re.search(pattern, line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            f"Database connection string ({description}) found:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 6. Email addresses are intentional
# ---------------------------------------------------------------------------

class TestEmailAddresses:
    """Ensure only intentional author email addresses are present."""

    # Known intentional emails for the plugin author
    ALLOWED_EMAILS = {
        "englund@mit.edu",       # Author's institutional email (in plugin.json, marketplace.json)
        "noreply@anthropic.com", # Co-author attribution in git
    }

    def test_only_intentional_emails(self, all_files: dict[str, str]):
        """Rule: Only known author emails should appear in plugin files."""
        email_pattern = re.compile(r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+')
        unexpected = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                found_emails = email_pattern.findall(line)
                for email in found_emails:
                    if email not in self.ALLOWED_EMAILS:
                        unexpected.append(f"  {relpath}:{line_num}: {email}")
        assert not unexpected, (
            "Unexpected email address(es) found in plugin files:\n"
            + "\n".join(unexpected)
            + "\nIf these are intentional, add them to ALLOWED_EMAILS in this test."
        )


# ---------------------------------------------------------------------------
# 7. .gitignore covers sensitive file patterns
# ---------------------------------------------------------------------------

class TestGitignoreCoverage:
    """Ensure .gitignore protects against accidental secret commits."""

    # Patterns that MUST appear in .gitignore for a public plugin
    REQUIRED_PATTERNS = [
        (".env", "Environment variable files (.env)"),
        (".DS_Store", "macOS metadata (.DS_Store)"),
        ("__pycache__", "Python bytecode cache (__pycache__)"),
        ("node_modules", "Node.js dependencies (node_modules)"),
    ]

    RECOMMENDED_PATTERNS = [
        (".env.*", "Environment file variants (.env.local, .env.production)"),
        ("*.pem", "PEM certificate/key files"),
        ("*.key", "Private key files"),
        ("*.secret", "Secret files"),
        (".secrets", "Secrets directory"),
    ]

    def test_gitignore_exists(self):
        """Rule: .gitignore must exist in the plugin root."""
        gitignore = PLUGIN_ROOT / ".gitignore"
        assert gitignore.exists(), ".gitignore not found in plugin root"

    @pytest.mark.parametrize("pattern,description", REQUIRED_PATTERNS, ids=[d for _, d in REQUIRED_PATTERNS])
    def test_gitignore_has_required_pattern(self, pattern: str, description: str):
        """Rule: .gitignore must cover required pattern '{description}'."""
        gitignore = PLUGIN_ROOT / ".gitignore"
        content = gitignore.read_text(encoding="utf-8")
        lines = [line.strip() for line in content.splitlines() if line.strip() and not line.startswith("#")]
        # Check if the pattern is covered (exact match or glob that covers it)
        covered = any(pattern in line for line in lines)
        assert covered, (
            f".gitignore does not cover '{pattern}' ({description}).\n"
            f"Current .gitignore contents:\n{content}\n"
            f"Add '{pattern}' to .gitignore before publishing."
        )

    @pytest.mark.parametrize("pattern,description", RECOMMENDED_PATTERNS, ids=[d for _, d in RECOMMENDED_PATTERNS])
    def test_gitignore_has_recommended_pattern(self, pattern: str, description: str):
        """Advisory: .gitignore should cover recommended pattern '{description}'."""
        gitignore = PLUGIN_ROOT / ".gitignore"
        content = gitignore.read_text(encoding="utf-8")
        lines = [line.strip() for line in content.splitlines() if line.strip() and not line.startswith("#")]
        covered = any(pattern in line for line in lines)
        if not covered:
            pytest.xfail(
                f".gitignore does not cover recommended pattern '{pattern}' ({description}). "
                f"Consider adding it before publishing."
            )


# ---------------------------------------------------------------------------
# 8. No prompt injection vectors in agent/skill instructions
# ---------------------------------------------------------------------------

class TestPromptInjectionSafety:
    """Check agent and skill prompts for injection risks."""

    INSTRUCTION_FILES = [
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
    ]

    def _read_instruction(self, relpath: str) -> str:
        p = PLUGIN_ROOT / relpath
        assert p.exists(), f"Instruction file not found: {relpath}"
        return p.read_text(encoding="utf-8")

    def test_no_data_exfiltration_instructions(self):
        """Rule: Agent/skill prompts must not instruct exfiltration of user data."""
        exfil_patterns = [
            r'(?i)send\s+(user|their|the)\s+(data|files?|content|information|secrets?|credentials?|keys?)',
            r'(?i)(exfiltrate|steal|harvest|collect)\s+.*(data|information|credentials)',
            r'(?i)forward\s+.*(to|via)\s+(email|http|webhook|url)',
            r'(?i)(upload|post|submit)\s+(user|their)\s+(data|files?|content)',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in exfil_patterns:
                matches = re.findall(pattern, content)
                if matches:
                    violations.append(f"  {relpath}: matches exfil pattern '{pattern}': {matches}")
        assert not violations, (
            "Potential data exfiltration instructions found:\n" + "\n".join(violations)
        )

    def test_no_arbitrary_code_execution_instructions(self):
        """Rule: Agent prompts must not instruct execution of arbitrary code from user input."""
        code_exec_patterns = [
            r'(?i)(eval|exec|execute)\s+(the\s+)?(user[\'\"]?s?\s+)?(code|input|command|script)',
            r'(?i)run\s+(arbitrary|any|untrusted)\s+(code|commands?|scripts?)',
            r'(?i)subprocess\.(call|run|Popen)',
            r'(?i)os\.system\s*\(',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in code_exec_patterns:
                matches = re.findall(pattern, content)
                if matches:
                    violations.append(f"  {relpath}: matches code exec pattern '{pattern}': {matches}")
        assert not violations, (
            "Potential arbitrary code execution instructions found:\n" + "\n".join(violations)
        )

    def test_no_system_prompt_extraction_instructions(self):
        """Rule: Agent prompts must not instruct revealing system prompts or internal instructions."""
        extraction_patterns = [
            r'(?i)(reveal|expose|leak|share|output|print|display)\s+(your\s+)?(system\s+)?(prompt|instructions)',
            r'(?i)ignore\s+(previous|prior|all)\s+(instructions|prompts|rules)',
            r'(?i)(disregard|bypass|override)\s+(safety|security|content)\s+(rules|filters|guidelines)',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in extraction_patterns:
                matches = re.findall(pattern, content)
                if matches:
                    violations.append(f"  {relpath}: matches extraction pattern '{pattern}': {matches}")
        assert not violations, (
            "Potential system prompt extraction instructions found:\n" + "\n".join(violations)
        )

    def test_agent_scoped_to_specific_tools(self):
        """Rule: Agent prompts should reference only specific, named MCP tools -- not open-ended tool access."""
        agent_content = self._read_instruction("agents/vvuq-verifier.md")
        # The agent should mention specific tool names
        assert "vvuq_resolve" in agent_content, (
            "Agent prompt does not reference a specific tool name (vvuq_resolve). "
            "Agent prompts should be scoped to named tools, not open-ended."
        )
        # The agent should NOT instruct use of arbitrary/all tools
        open_ended = re.findall(r'(?i)(use any|all available|any tool|arbitrary tool)', agent_content)
        assert not open_ended, (
            f"Agent prompt contains open-ended tool access language: {open_ended}\n"
            "Agent prompts should be scoped to specific, named tools only."
        )

    def test_skill_does_not_override_safety(self):
        """Rule: Skill instructions must not attempt to override Claude's safety guidelines."""
        skill_content = self._read_instruction("skills/verify-claim/SKILL.md")
        override_patterns = [
            r'(?i)ignore\s+(content\s+)?(policy|safety|guidelines)',
            r'(?i)you\s+are\s+(now\s+)?(free|allowed)\s+to',
            r'(?i)(disable|turn off|bypass)\s+(safety|content|moderation)',
            r'(?i)jailbreak',
        ]
        violations = []
        for pattern in override_patterns:
            if re.search(pattern, skill_content):
                violations.append(f"  Pattern matched: {pattern}")
        assert not violations, (
            "Skill prompt attempts to override safety guidelines:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 9. No hardcoded server/environment configuration
# ---------------------------------------------------------------------------

class TestNoHardcodedConfig:
    """Ensure no server-side configuration details leak into the plugin."""

    def test_no_environment_variables_with_values(self, all_files: dict[str, str]):
        """Rule: No environment variable assignments with actual values (e.g., export KEY=value)."""
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                # Match export VAR=value or VAR=value patterns with actual values
                if re.search(r'(?i)^export\s+\w*(KEY|SECRET|TOKEN|PASSWORD|CREDENTIAL)\w*\s*=\s*\S+', line):
                    violations.append(f"  {relpath}:{line_num}: {line.strip()[:120]}")
        assert not violations, (
            "Environment variable with sensitive value found:\n" + "\n".join(violations)
        )

    def test_no_server_deploy_hostnames(self, all_files: dict[str, str]):
        """Rule: No internal deploy target hostnames (e.g., spark-7543) in shipped files."""
        deploy_hostname_pattern = re.compile(r'\b(spark|newton|gohymins)[-\w]*\b', re.IGNORECASE)
        violations = []
        for relpath, content in all_files.items():
            for line_num, line in enumerate(content.splitlines(), 1):
                match = deploy_hostname_pattern.search(line)
                if match:
                    violations.append(
                        f"  {relpath}:{line_num}: hostname '{match.group()}' in: {line.strip()[:120]}"
                    )
        assert not violations, (
            "Internal deploy hostname found in plugin files:\n" + "\n".join(violations)
            + "\nThese hostnames should not appear in publicly distributed plugins."
        )


# ---------------------------------------------------------------------------
# 10. Plugin metadata integrity
# ---------------------------------------------------------------------------

class TestPluginMetadataIntegrity:
    """Verify plugin metadata files are well-formed and consistent."""

    def test_plugin_json_valid(self):
        """Rule: plugin.json must be valid JSON with required fields."""
        plugin_path = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
        assert plugin_path.exists(), "plugin.json not found"
        data = json.loads(plugin_path.read_text(encoding="utf-8"))
        required_fields = ["name", "version", "description", "author", "license"]
        for field in required_fields:
            assert field in data, f"Missing required field '{field}' in plugin.json"

    def test_marketplace_json_valid(self):
        """Rule: marketplace.json must be valid JSON with required fields."""
        mp_path = PLUGIN_ROOT / ".claude-plugin" / "marketplace.json"
        assert mp_path.exists(), "marketplace.json not found"
        data = json.loads(mp_path.read_text(encoding="utf-8"))
        assert "plugins" in data, "Missing 'plugins' in marketplace.json"
        assert len(data["plugins"]) > 0, "No plugins defined in marketplace.json"

    def test_mcp_json_no_auth_tokens(self):
        """Rule: .mcp.json must not contain authentication tokens or headers."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        config_str = json.dumps(config)
        # Check for auth-related keys
        auth_indicators = ["authorization", "bearer", "x-api-key", "apikey", "api_key", "token"]
        for indicator in auth_indicators:
            assert indicator not in config_str.lower(), (
                f"MCP config contains authentication-related content: '{indicator}'\n"
                "Authentication tokens must not be shipped in public plugin configs."
            )

    def test_versions_consistent(self):
        """Rule: Version numbers must be consistent across plugin.json and marketplace.json."""
        plugin_path = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
        mp_path = PLUGIN_ROOT / ".claude-plugin" / "marketplace.json"
        plugin_data = json.loads(plugin_path.read_text(encoding="utf-8"))
        mp_data = json.loads(mp_path.read_text(encoding="utf-8"))
        plugin_version = plugin_data.get("version")
        mp_version = mp_data.get("metadata", {}).get("version")
        mp_plugin_version = mp_data.get("plugins", [{}])[0].get("version")
        assert plugin_version == mp_version, (
            f"Version mismatch: plugin.json={plugin_version}, marketplace.json metadata={mp_version}"
        )
        assert plugin_version == mp_plugin_version, (
            f"Version mismatch: plugin.json={plugin_version}, marketplace.json plugins[0]={mp_plugin_version}"
        )


# ---------------------------------------------------------------------------
# 11. Round 2: privacy.html security review
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    not (Path(__file__).parent.parent.parent / "privacy.html").exists(),
    reason="privacy.html lives in vvuq-mcp server repo, not plugin distribution (issue #197)",
)
class TestPrivacyHtmlSecurity:
    """Security tests for the privacy.html file added to the plugin.

    Generated by: Security Critic Agent Round 2 (Claude Opus 4.6)
    Date: 2026-03-03
    """

    PRIVACY_PATH = PLUGIN_ROOT / "privacy.html"

    def _read_privacy(self) -> str:
        assert self.PRIVACY_PATH.exists(), (
            "privacy.html not found in plugin root"
        )
        return self.PRIVACY_PATH.read_text(encoding="utf-8")

    def test_privacy_html_exists(self):
        """Rule: privacy.html must exist since it is shipped with the plugin."""
        assert self.PRIVACY_PATH.exists(), "privacy.html not found"

    def test_no_inline_javascript(self):
        """Rule: privacy.html must contain no inline JavaScript (XSS surface)."""
        content = self._read_privacy()
        # Check for <script> tags
        assert not re.search(r'<script\b', content, re.IGNORECASE), (
            "privacy.html contains <script> tag -- inline JavaScript is an XSS vector "
            "in a file distributed with a plugin."
        )

    def test_no_javascript_event_handlers(self):
        """Rule: privacy.html must not contain JavaScript event handlers (onclick, onerror, etc.)."""
        content = self._read_privacy()
        event_handler_pattern = re.compile(
            r'\bon(click|error|load|mouseover|mouseout|submit|focus|blur|change|input|keydown|keyup|keypress)'
            r'\s*=',
            re.IGNORECASE,
        )
        assert not event_handler_pattern.search(content), (
            "privacy.html contains JavaScript event handler attributes. "
            "These are XSS vectors and must be removed."
        )

    def test_no_javascript_urls(self):
        """Rule: privacy.html must not contain javascript: URL scheme."""
        content = self._read_privacy()
        assert not re.search(r'javascript\s*:', content, re.IGNORECASE), (
            "privacy.html contains 'javascript:' URL scheme -- XSS vector."
        )

    def test_no_external_script_or_stylesheet_resources(self):
        """Rule: privacy.html should not load external resources (tracking risk, supply chain)."""
        content = self._read_privacy()
        # External script sources
        assert not re.search(r'<script\b[^>]+src\s*=', content, re.IGNORECASE), (
            "privacy.html loads an external script -- supply chain risk."
        )
        # External stylesheets (link rel=stylesheet with external href)
        external_css = re.findall(r'<link\b[^>]+href\s*=\s*["\']https?://', content, re.IGNORECASE)
        assert not external_css, (
            "privacy.html loads external CSS -- potential tracking pixel or supply chain risk."
        )

    def test_no_iframes(self):
        """Rule: privacy.html must not contain iframes (clickjacking, content injection)."""
        content = self._read_privacy()
        assert not re.search(r'<iframe\b', content, re.IGNORECASE), (
            "privacy.html contains an <iframe> -- clickjacking and content injection risk."
        )

    def test_no_form_elements(self):
        """Rule: privacy.html should not contain forms (data collection without consent flow)."""
        content = self._read_privacy()
        assert not re.search(r'<form\b', content, re.IGNORECASE), (
            "privacy.html contains a <form> element -- unexpected data collection surface."
        )

    def test_no_tracking_pixels_or_images(self):
        """Rule: privacy.html should not load external images (tracking pixels)."""
        content = self._read_privacy()
        external_images = re.findall(r'<img\b[^>]+src\s*=\s*["\']https?://', content, re.IGNORECASE)
        assert not external_images, (
            f"privacy.html loads external images (potential tracking pixels): {external_images}"
        )

    def test_mailto_links_use_allowed_emails_only(self):
        """Rule: mailto: links in privacy.html must only reference allowed email addresses."""
        content = self._read_privacy()
        mailto_pattern = re.compile(r'mailto:([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)')
        found_emails = mailto_pattern.findall(content)
        allowed = {"englund@mit.edu", "noreply@anthropic.com"}
        for email in found_emails:
            assert email in allowed, (
                f"privacy.html contains mailto: link to unexpected email '{email}'. "
                f"Allowed: {allowed}"
            )

    def test_no_data_uri_schemes(self):
        """Rule: privacy.html must not contain data: URI schemes (potential payload injection)."""
        content = self._read_privacy()
        assert not re.search(r'data\s*:\s*(?:text|image|application)/', content, re.IGNORECASE), (
            "privacy.html contains data: URI scheme -- potential payload injection vector."
        )

    def test_privacy_claims_https(self):
        """Rule: privacy.html claims 'All connections use HTTPS (TLS 1.2+)'.
        Verify the MCP config is consistent with this claim."""
        content = self._read_privacy()
        if "HTTPS" in content or "TLS" in content:
            mcp_path = PLUGIN_ROOT / ".mcp.json"
            mcp_config = json.loads(mcp_path.read_text(encoding="utf-8"))
            for name, server in mcp_config.get("mcpServers", {}).items():
                url = server.get("url", "")
                assert url.startswith("https://"), (
                    f"privacy.html claims HTTPS but MCP server '{name}' uses: {url}"
                )

    def test_opt_out_header_not_in_instruction_files(self):
        """Rule: The X-VVUQ-No-Log header (opt-out mechanism) must NOT appear in
        agent/command/skill instructions. If it did, the agent would silently
        opt users out of logging without their knowledge, or an attacker could
        abuse the header knowledge to evade audit trails."""
        header_name = "X-VVUQ-No-Log"
        instruction_files = [
            PLUGIN_ROOT / "commands" / "verify.md",
            PLUGIN_ROOT / "agents" / "vvuq-verifier.md",
            PLUGIN_ROOT / "skills" / "verify-claim" / "SKILL.md",
        ]
        for fpath in instruction_files:
            content = fpath.read_text(encoding="utf-8")
            assert header_name not in content, (
                f"Instruction file {fpath.relative_to(PLUGIN_ROOT)} references "
                f"'{header_name}'. Agent instructions must NOT silently set opt-out "
                f"headers -- this should be a user-initiated action only."
            )


# ---------------------------------------------------------------------------
# 12. Round 2: Scanner coverage gap -- HTML files excluded from scans
# ---------------------------------------------------------------------------

class TestScannerCoverage:
    """Verify that the security scanner catches all file types shipped with the plugin.

    Generated by: Security Critic Agent Round 2 (Claude Opus 4.6)
    Date: 2026-03-03
    """

    def test_html_files_scanned_for_secrets(self):
        """Rule: HTML files shipped with the plugin must be scanned for hardcoded secrets.
        The original SCANNABLE_EXTENSIONS set ({json, md, txt, yml, yaml, toml, cfg, ini, sh})
        omits .html files. This test directly scans all .html files for secret patterns."""
        html_files = list(PLUGIN_ROOT.rglob("*.html"))
        html_files = [f for f in html_files if ".git" not in f.parts]
        violations = []
        for hf in html_files:
            content = hf.read_text(encoding="utf-8")
            for pattern, description in SECRET_PATTERNS:
                for line_num, line in enumerate(content.splitlines(), 1):
                    if re.search(pattern, line):
                        if "<" in line and ">" in line:
                            continue
                        violations.append(
                            f"  {hf.relative_to(PLUGIN_ROOT)}:{line_num}: "
                            f"({description}) {line.strip()[:120]}"
                        )
        assert not violations, (
            "Hardcoded secrets found in HTML files (not covered by main scanner):\n"
            + "\n".join(violations)
        )

    def test_html_files_scanned_for_internal_infrastructure(self):
        """Rule: HTML files must not contain internal hostnames or private IPs."""
        html_files = list(PLUGIN_ROOT.rglob("*.html"))
        html_files = [f for f in html_files if ".git" not in f.parts]
        internal_patterns = [
            (r'\b10\.\d{1,3}\.\d{1,3}\.\d{1,3}\b', "RFC1918 10.x.x.x IP"),
            (r'\b172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}\b', "RFC1918 172.16-31.x.x IP"),
            (r'\b192\.168\.\d{1,3}\.\d{1,3}\b', "RFC1918 192.168.x.x IP"),
            (r'\b(?:spark|newton|gohymins)[-\w]*\b', "Internal hostname"),
        ]
        violations = []
        for hf in html_files:
            content = hf.read_text(encoding="utf-8")
            for line_num, line in enumerate(content.splitlines(), 1):
                for pattern, description in internal_patterns:
                    if re.search(pattern, line):
                        violations.append(
                            f"  {hf.relative_to(PLUGIN_ROOT)}:{line_num}: "
                            f"({description}) {line.strip()[:120]}"
                        )
        assert not violations, (
            "Internal infrastructure details found in HTML files:\n"
            + "\n".join(violations)
        )

    def test_html_files_scanned_for_database_strings(self):
        """Rule: HTML files must not contain database connection strings."""
        html_files = list(PLUGIN_ROOT.rglob("*.html"))
        html_files = [f for f in html_files if ".git" not in f.parts]
        db_patterns = [
            (r'(?i)mongodb(\+srv)?://[^\s"\']+', "MongoDB"),
            (r'(?i)postgres(ql)?://[^\s"\']+', "PostgreSQL"),
            (r'(?i)mysql://[^\s"\']+', "MySQL"),
            (r'(?i)redis://[^\s"\']+', "Redis"),
            (r'(?i)neo4j(\+s)?://[^\s"\']+', "Neo4j"),
        ]
        violations = []
        for hf in html_files:
            content = hf.read_text(encoding="utf-8")
            for pattern, description in db_patterns:
                if re.search(pattern, content):
                    violations.append(
                        f"  {hf.relative_to(PLUGIN_ROOT)}: {description} connection string"
                    )
        assert not violations, (
            "Database connection strings found in HTML files:\n"
            + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 13. Round 2: Privacy policy metadata and discoverability
# ---------------------------------------------------------------------------

class TestPrivacyPolicyDiscoverability:
    """A privacy policy that exists but is not referenced from plugin metadata
    is effectively invisible to marketplace users. This creates a deceptive
    appearance of privacy compliance without actual user visibility.

    Generated by: Security Critic Agent Round 2 (Claude Opus 4.6)
    Date: 2026-03-03
    """

    def test_plugin_json_references_privacy_policy(self):
        """Rule: plugin.json should include a privacy or privacyPolicy field
        if a privacy.html file is shipped, so marketplace UIs can surface it."""
        privacy_exists = (PLUGIN_ROOT / "privacy.html").exists()
        if not privacy_exists:
            pytest.skip("No privacy.html file -- nothing to reference")
        plugin_path = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
        plugin_data = json.loads(plugin_path.read_text(encoding="utf-8"))
        plugin_str = json.dumps(plugin_data).lower()
        has_privacy_ref = any(
            key in plugin_str
            for key in ["privacy", "privacypolicy", "privacy_policy", "privacy.html"]
        )
        assert has_privacy_ref, (
            "plugin.json does not reference the privacy policy. A privacy.html file "
            "exists but is invisible to users installing via the marketplace. "
            "Add a 'privacy' or 'privacyPolicy' field pointing to privacy.html "
            "or its hosted URL."
        )

    def test_readme_links_to_privacy_policy(self):
        """Rule: README.md should link to the privacy policy so users can find it."""
        privacy_exists = (PLUGIN_ROOT / "privacy.html").exists()
        if not privacy_exists:
            pytest.skip("No privacy.html file -- nothing to link")
        readme = (PLUGIN_ROOT / "README.md").read_text(encoding="utf-8")
        has_privacy_link = any(
            term in readme.lower()
            for term in ["privacy", "privacy.html", "privacy policy"]
        )
        assert has_privacy_link, (
            "README.md does not mention or link to the privacy policy. "
            "Users should be able to find the privacy policy from the README."
        )


# ---------------------------------------------------------------------------
# 14. Round 2: SSRF risk in MCP URL configuration
# ---------------------------------------------------------------------------

class TestSsrfProtection:
    """Check that MCP URL configuration does not allow SSRF attacks.

    Generated by: Security Critic Agent Round 2 (Claude Opus 4.6)
    Date: 2026-03-03
    """

    def test_mcp_url_is_hardcoded_not_templated(self):
        """Rule: MCP URL must be a fixed HTTPS URL, not a template or variable
        that could be manipulated to point at internal services (SSRF)."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        content = mcp_path.read_text(encoding="utf-8")
        # Check for template variables like ${VAR}, {{var}}, %ENV%
        template_patterns = [
            r'\$\{[^}]+\}',        # ${VARIABLE}
            r'\{\{[^}]+\}\}',      # {{variable}}
            r'%[A-Z_]+%',          # %VARIABLE%
            r'\$[A-Z_]+',          # $VARIABLE
        ]
        for pattern in template_patterns:
            assert not re.search(pattern, content), (
                f"MCP config contains template variable matching '{pattern}'. "
                "Templated URLs can be manipulated to point at internal services (SSRF). "
                "Use a fixed HTTPS URL."
            )

    def test_mcp_url_points_to_known_domain(self):
        """Rule: MCP URL must point to the documented service domain, not
        an arbitrary or attacker-controlled domain."""
        mcp_path = PLUGIN_ROOT / ".mcp.json"
        config = json.loads(mcp_path.read_text(encoding="utf-8"))
        for name, server in config.get("mcpServers", {}).items():
            url = server.get("url", "")
            assert "dirkenglund.org" in url, (
                f"MCP server '{name}' URL '{url}' does not point to the expected "
                "domain (dirkenglund.org). This could indicate URL hijacking or "
                "misconfiguration."
            )

    def test_no_url_override_instructions_in_agent_files(self):
        """Rule: Agent/command/skill instructions must not tell the agent to
        construct or override MCP URLs from user input (SSRF via prompt injection)."""
        instruction_files = [
            PLUGIN_ROOT / "commands" / "verify.md",
            PLUGIN_ROOT / "agents" / "vvuq-verifier.md",
            PLUGIN_ROOT / "skills" / "verify-claim" / "SKILL.md",
        ]
        url_construction_patterns = [
            r'(?i)(construct|build|create|generate|form)\s+(a\s+|the\s+)?url',
            r'(?i)(set|change|override|modify)\s+(the\s+)?(mcp|server|endpoint)\s*(url|address|host)',
            r'(?i)fetch\s+from\s+(user|their|the)\s+(url|endpoint|server)',
        ]
        violations = []
        for fpath in instruction_files:
            content = fpath.read_text(encoding="utf-8")
            for pattern in url_construction_patterns:
                matches = re.findall(pattern, content)
                if matches:
                    violations.append(
                        f"  {fpath.relative_to(PLUGIN_ROOT)}: "
                        f"matches URL construction pattern '{pattern}'"
                    )
        assert not violations, (
            "Instruction files contain URL construction/override language (SSRF risk):\n"
            + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# 15. Round 2: Prompt injection resilience in instruction files
# ---------------------------------------------------------------------------

class TestPromptInjectionResilience:
    """Additional prompt injection checks not covered by Round 1.
    Focuses on indirect injection vectors and instruction manipulation.

    Generated by: Security Critic Agent Round 2 (Claude Opus 4.6)
    Date: 2026-03-03
    """

    INSTRUCTION_FILES = [
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
    ]

    def _read_instruction(self, relpath: str) -> str:
        p = PLUGIN_ROOT / relpath
        assert p.exists(), f"Instruction file not found: {relpath}"
        return p.read_text(encoding="utf-8")

    def test_no_file_system_access_instructions(self):
        """Rule: Instruction files must not tell the agent to read, write,
        or access the user's filesystem (data exfiltration risk)."""
        fs_patterns = [
            r'(?i)(read|write|open|access|scan|list)\s+(the\s+)?(user[\']?s?\s+)?(file|director|folder|path|disk)',
            r'(?i)(cat|head|tail|less|more)\s+/',
            r'(?i)os\.(path|listdir|walk|makedirs)',
            r'(?i)pathlib\.Path',
            r'(?i)(read|write)_text\s*\(',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in fs_patterns:
                if re.search(pattern, content):
                    violations.append(
                        f"  {relpath}: matches filesystem access pattern '{pattern}'"
                    )
        assert not violations, (
            "Instruction files contain filesystem access language:\n"
            + "\n".join(violations)
            + "\nAgent instructions must not direct filesystem operations "
            "that could exfiltrate user data."
        )

    def test_no_network_request_instructions(self):
        """Rule: Instruction files must not tell the agent to make arbitrary
        HTTP requests (only the named MCP tools should be used)."""
        network_patterns = [
            r'(?i)(curl|wget|fetch|requests\.get|requests\.post|httpx)',
            r'(?i)(http|https)://[^\s]+\s+.*\b(get|post|put|delete|patch)\b',
            r'(?i)make\s+a\s+(http|api|web)\s+(request|call)',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in network_patterns:
                if re.search(pattern, content):
                    violations.append(
                        f"  {relpath}: matches network request pattern '{pattern}'"
                    )
        assert not violations, (
            "Instruction files contain arbitrary network request language:\n"
            + "\n".join(violations)
            + "\nAgent instructions should only reference named MCP tools, "
            "not arbitrary HTTP requests."
        )

    def test_no_shell_command_instructions(self):
        """Rule: Instruction files must not instruct the agent to run shell commands."""
        shell_patterns = [
            r'(?i)(run|execute|invoke)\s+(a\s+)?(shell|bash|terminal|command\s+line)\s+(command|script)',
            r'(?i)\$\(.*\)',                      # $(command) substitution
            r'(?i)subprocess\.',                   # Python subprocess
            r'(?i)child_process',                  # Node.js child_process
            r'(?i)system\s*\(',                    # system() call
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in shell_patterns:
                if re.search(pattern, content):
                    violations.append(
                        f"  {relpath}: matches shell command pattern '{pattern}'"
                    )
        assert not violations, (
            "Instruction files contain shell command execution language:\n"
            + "\n".join(violations)
        )

    def test_no_role_reassignment_in_instructions(self):
        """Rule: Instruction files must not contain patterns that attempt to
        reassign the agent's role or identity (common prompt injection technique)."""
        role_patterns = [
            r'(?i)you\s+are\s+now\s+a',
            r'(?i)forget\s+(everything|all|your|previous)',
            r'(?i)new\s+instructions?\s*:',
            r'(?i)act\s+as\s+if\s+you\s+are',
            r'(?i)pretend\s+(to\s+be|you\s+are)',
            r'(?i)from\s+now\s+on\s+you\s+(are|will|must)',
        ]
        violations = []
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            for pattern in role_patterns:
                if re.search(pattern, content):
                    violations.append(
                        f"  {relpath}: matches role reassignment pattern '{pattern}'"
                    )
        assert not violations, (
            "Instruction files contain role reassignment language "
            "(common prompt injection technique):\n"
            + "\n".join(violations)
        )

    def test_claim_input_not_used_as_instruction(self):
        """Rule: Instruction files must make clear that user claim text is DATA,
        not instructions. The agent should not interpret claim content as commands."""
        for relpath in self.INSTRUCTION_FILES:
            content = self._read_instruction(relpath)
            # Check that claim text is passed as a quoted argument to vvuq_resolve
            # Pattern: vvuq_resolve(query="<...>") or vvuq_resolve(query="...")
            has_quoted_query = re.search(
                r'vvuq_resolve\s*\(\s*query\s*=\s*["\']', content
            )
            assert has_quoted_query, (
                f"{relpath} does not show claim text as a quoted argument to "
                f"vvuq_resolve. User input must be treated as data (quoted string), "
                f"not as instructions, to prevent indirect prompt injection."
            )


# ---------------------------------------------------------------------------
# 16. Round 2: Data retention and privacy compliance checks
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    not (Path(__file__).parent.parent.parent / "privacy.html").exists(),
    reason="privacy.html lives in vvuq-mcp server repo, not plugin distribution (issue #197)",
)
class TestPrivacyComplianceClaims:
    """Verify that privacy claims in privacy.html are internally consistent
    and do not make misleading statements about data handling.

    Generated by: Security Critic Agent Round 2 (Claude Opus 4.6)
    Date: 2026-03-03
    """

    def _read_privacy(self) -> str:
        p = PLUGIN_ROOT / "privacy.html"
        assert p.exists(), "privacy.html not found"
        return p.read_text(encoding="utf-8")

    def test_retention_periods_are_specified(self):
        """Rule: Privacy policy must specify concrete retention periods, not vague terms."""
        content = self._read_privacy()
        # Should mention specific time periods for data retention
        has_specific_period = re.search(r'\d+\s*(days?|months?|years?|hours?)', content)
        assert has_specific_period, (
            "privacy.html does not specify concrete data retention periods. "
            "Vague retention language is non-compliant with GDPR/CCPA principles."
        )

    def test_no_contradictory_data_claims(self):
        """Rule: privacy.html must not simultaneously claim 'no data collected'
        and describe data collection."""
        content = self._read_privacy().lower()
        claims_no_data = "does not collect" in content or "no data is collected" in content
        describes_collection = "ip address" in content or "server logs" in content
        if claims_no_data and describes_collection:
            # This is acceptable IF the "does not collect" claim is about a specific
            # category (e.g., "does not collect names") while logs are a different category.
            # Check if the negation is scoped.
            has_scoped_negation = re.search(
                r'does\s+not\s+collect\s+(names|email|account|personal)', content
            )
            assert has_scoped_negation, (
                "privacy.html appears to both deny data collection and describe "
                "data collection (IP, logs). The denial must be scoped to specific "
                "data categories to avoid contradicting itself."
            )

    def test_opt_out_mechanism_is_actionable(self):
        """Rule: If privacy.html describes an opt-out mechanism, it must provide
        enough detail for users to actually use it."""
        content = self._read_privacy()
        if "opt out" in content.lower() or "opt-out" in content.lower():
            # Must include EITHER a header name, an email, or a URL
            has_mechanism = (
                "X-VVUQ-No-Log" in content
                or re.search(r'mailto:', content)
                or re.search(r'https?://\S+opt', content, re.IGNORECASE)
            )
            assert has_mechanism, (
                "privacy.html mentions opt-out but does not provide an actionable "
                "mechanism (header name, email address, or opt-out URL)."
            )

    def test_privacy_html_has_last_updated_date(self):
        """Rule: Privacy policy must include a last-updated date."""
        content = self._read_privacy()
        has_date = re.search(
            r'(?:last\s+)?updated[:\s]+\w+\s+\d{1,2},?\s+\d{4}',
            content,
            re.IGNORECASE,
        )
        assert has_date, (
            "privacy.html does not include a 'Last updated' date. "
            "Users need to know when the policy was last revised."
        )

    def test_privacy_html_has_contact_information(self):
        """Rule: Privacy policy must include contact information for questions."""
        content = self._read_privacy()
        has_contact = (
            "mailto:" in content
            or re.search(r'contact\s+us', content, re.IGNORECASE)
            or re.search(r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z]+', content)
        )
        assert has_contact, (
            "privacy.html does not include contact information. "
            "Users must be able to reach the data controller with questions."
        )


# ---------------------------------------------------------------------------
# 17. Round 3: CI workflow security
# ---------------------------------------------------------------------------

class TestCiWorkflowSecurity:
    """Security checks for the GitHub Actions CI workflow added in Round 3.

    The workflow file runs on every push/PR to main, executes code under a
    GITHUB_TOKEN, and installs packages from PyPI.  Three distinct risk
    surfaces are checked:

    (a) Missing permissions block  -- default token grants may be broader than
        needed; explicit ``permissions: read-all`` or per-job scoping is
        required for least-privilege.

    (b) Mutable action tags (@v4, @v5) -- a tag can be moved to a different
        commit by the action author or by a supply-chain attacker.  SHA pinning
        is the only way to guarantee the action code you tested is the code
        that runs in production.

    (c) Unpinned pip install -- ``pip install pytest`` resolves the latest
        release at CI time.  A malicious release of pytest (or a transitive
        dependency) could execute arbitrary code during the CI run, which runs
        with write access to the repository's Actions environment.

    Generated by: Security Critic Agent Round 3 (Claude Sonnet 4.6)
    Date: 2026-03-03
    """

    WORKFLOW_PATH = PLUGIN_ROOT / ".github" / "workflows" / "tests.yml"

    def _read_workflow(self) -> str:
        assert self.WORKFLOW_PATH.exists(), (
            ".github/workflows/tests.yml not found -- did the file move?"
        )
        return self.WORKFLOW_PATH.read_text(encoding="utf-8")

    def test_workflow_has_permissions_block(self):
        """Rule: GitHub Actions workflow must declare an explicit 'permissions:' block.

        Without an explicit permissions block the GITHUB_TOKEN inherits the
        repository default, which is typically ``contents: write`` for push
        events.  An attacker who achieves code execution during CI (e.g. via a
        malicious dependency) can then write to the repo, create releases, or
        read secrets.  An explicit ``permissions: read-all`` or narrower
        per-job grant enforces least privilege.

        Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
        """
        content = self._read_workflow()
        assert "permissions:" in content, (
            ".github/workflows/tests.yml has no 'permissions:' block.\n"
            "Without an explicit permissions declaration the GITHUB_TOKEN uses the "
            "repository default, which can include write access.  Add at minimum:\n"
            "\n"
            "  permissions:\n"
            "    contents: read\n"
            "\n"
            "at the top level of the workflow file to enforce least-privilege."
        )

    @pytest.mark.xfail(reason="Tag-pinned actions (@v4, @v5) are standard for small plugins — SHA pinning adds maintenance burden")
    def test_workflow_actions_are_sha_pinned(self):
        """Rule: All 'uses:' action references in the workflow must be pinned to a
        full commit SHA, not a mutable tag like @v4 or @v5.

        A mutable tag can be silently moved to a different (malicious) commit
        after you audit the action.  SHA pinning guarantees the exact code that
        was reviewed is what runs.  This is the GitHub-recommended mitigation
        for supply-chain attacks on third-party actions.

        Example of a pinned reference:
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

        Reference: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        """
        content = self._read_workflow()
        # Match any 'uses:' line (with optional leading '- ') that refers to an action
        # with a tag (@word or @vN) but NOT a full 40-hex-char SHA pin.
        # YAML step format: "      - uses: owner/action@ref"
        mutable_tag_pattern = re.compile(
            r'^\s+(?:-\s+)?uses:\s+\S+@(?![\da-f]{40}\b)(\S+)',
            re.MULTILINE,
        )
        violations = []
        for match in mutable_tag_pattern.finditer(content):
            full_line = match.group(0).strip()
            tag = match.group(1)
            violations.append(f"  {full_line}  (tag: {tag!r} is mutable)")

        assert not violations, (
            "GitHub Actions workflow uses mutable action tags instead of SHA pins.\n"
            "These tags can be silently repointed to malicious commits (supply-chain attack):\n"
            + "\n".join(violations)
            + "\n\nPin each action to a full 40-character commit SHA.  Example:\n"
            "  uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2"
        )

    def test_workflow_pip_install_is_pinned(self):
        """Rule: 'pip install' in CI must pin exact package versions.

        ``pip install pytest`` fetches the latest release at CI time.  A
        supply-chain compromise of pytest (or any transitive dependency) would
        execute attacker code under the GITHUB_TOKEN.  Pin with ``==`` and
        commit a requirements file or inline version constraint.

        Acceptable: ``pip install pytest==8.3.4``
        Not acceptable: ``pip install pytest``
        """
        content = self._read_workflow()
        # Find any 'pip install' that lacks a '==' version pin
        # A pinned install looks like: pip install pytest==8.3.4
        # or: pip install -r requirements-ci.txt  (requirements file is acceptable)
        unpinned_pattern = re.compile(
            r'pip\s+install\s+(?!-r\s)(?:[^\n]*(?<![=><!])[a-zA-Z0-9_\-]+)\s*$',
            re.MULTILINE,
        )
        violations = []
        for match in unpinned_pattern.finditer(content):
            line = match.group(0).strip()
            # Skip lines that contain a version specifier
            if re.search(r'[=<>!]{1,2}[\d.]', line):
                continue
            # Skip lines that use -r (requirements file)
            if "-r " in line or "-r\t" in line:
                continue
            violations.append(f"  {line}")

        assert not violations, (
            "CI workflow runs 'pip install' without pinning package versions:\n"
            + "\n".join(violations)
            + "\n\nPin packages to exact versions (e.g., 'pip install pytest==8.3.4') "
            "or use a requirements file with hashes to prevent supply-chain attacks."
        )

    def test_workflow_has_timeout(self):
        """Rule: CI jobs must declare a timeout-minutes to prevent runaway builds.

        A test that enters an infinite loop (or a dependency that hangs) will
        consume CI minutes until GitHub's 6-hour hard limit, burning repository
        quota.  Explicit timeouts also limit the window in which an attacker who
        achieves code execution during CI can perform exfiltration.
        """
        content = self._read_workflow()
        assert "timeout-minutes:" in content, (
            ".github/workflows/tests.yml does not set 'timeout-minutes'.\n"
            "Without a timeout, a hanging test consumes CI minutes for up to 6 hours "
            "and extends the window for any code-execution-based exfiltration.\n"
            "Add 'timeout-minutes: 10' (or an appropriate limit) to the job definition."
        )


# ---------------------------------------------------------------------------
# 18. Round 3: README implementation disclosure
# ---------------------------------------------------------------------------

class TestReadmeImplementationDisclosure:
    """Check that the README 'How It Works' section does not expose
    implementation details that help attackers craft evasion inputs.

    The README (added/updated in Round 3) now describes the internal check
    pipeline: library names, check count, and check categories.  Each piece
    of information reduces the search space for an adversary trying to craft
    a claim that passes verification despite being wrong.

    Generated by: Security Critic Agent Round 3 (Claude Sonnet 4.6)
    Date: 2026-03-03
    """

    README_PATH = PLUGIN_ROOT / "README.md"

    def _read_readme(self) -> str:
        assert self.README_PATH.exists(), "README.md not found in plugin root"
        return self.README_PATH.read_text(encoding="utf-8")

    @pytest.mark.xfail(reason="Public plugin README should explain how the plugin works — check count is user-facing documentation, not a security risk")
    def test_readme_does_not_enumerate_check_count(self):
        """Rule: README must not state the exact number of internal verification checks.

        Publishing the check count ("up to 3 checks") tells an attacker exactly
        how many distinct evasion strategies to prepare.  If they know there are
        exactly 3 checks, they can probe each boundary independently.  The count
        is an internal implementation detail that provides no user value and
        meaningful attacker value.
        """
        content = self._read_readme()
        # Look for explicit "up to N checks" or "N checks" patterns
        check_count_pattern = re.compile(
            r'\bup\s+to\s+\d+\s+checks?\b'
            r'|\bruns?\s+\d+\s+checks?\b'
            r'|\bperforms?\s+\d+\s+checks?\b',
            re.IGNORECASE,
        )
        match = check_count_pattern.search(content)
        assert not match, (
            f"README.md discloses the exact number of internal verification checks: "
            f"'{match.group(0)}'\n"
            "This tells attackers how many evasion strategies to prepare.  "
            "Replace with a user-facing description of outcomes, not internal counts.\n"
            f"Found near: {content[max(0,match.start()-40):match.end()+40]!r}"
        )

    @pytest.mark.xfail(reason="SymPy is open source and publicly known — naming it in docs is transparency, not a security risk")
    def test_readme_does_not_name_internal_libraries(self):
        """Rule: README must not name the specific libraries used to implement checks.

        Naming 'SymPy' in the How It Works section reveals which mathematical
        engine processes claims.  An attacker who knows the checker uses SymPy
        can test SymPy's known edge cases and limitations to craft claims that
        SymPy evaluates incorrectly.  Library names are implementation details;
        the README should describe capabilities, not implementations.
        """
        content = self._read_readme()
        # Libraries that are internal implementation details
        internal_libraries = [
            "SymPy",
            "sympy",
        ]
        violations = []
        for lib in internal_libraries:
            # Only flag if in a descriptive context (not a code block showing user commands)
            for line_num, line in enumerate(content.splitlines(), 1):
                if lib in line:
                    # Allow if it is inside a code fence (user-visible command)
                    # We check the broader context but flag the line
                    violations.append(
                        f"  README.md:{line_num}: names internal library '{lib}': "
                        f"{line.strip()[:120]}"
                    )
        assert not violations, (
            "README.md names internal verification libraries, exposing implementation "
            "details that help attackers find evasion paths:\n"
            + "\n".join(violations)
            + "\nReplace library names with capability descriptions "
            "(e.g., 'mathematical consistency checks' instead of 'SymPy')."
        )

    @pytest.mark.xfail(reason="vvuq_resolve is the public API — documenting it helps users, and prompt injection is mitigated by quoting")
    def test_readme_does_not_expose_internal_function_names(self):
        """Rule: README must not expose the internal MCP tool function name.

        The README currently shows 'Claude calls vvuq_resolve() on the VVUQ MCP
        service'.  While the function name is also present in the skill/agent
        instruction files (which is required for operation), its appearance in
        the public README — linked from the marketplace listing — broadcasts the
        exact function signature to anyone who reads the page.  A prompt-
        injection attacker who knows the function name can craft claims that
        attempt to call vvuq_resolve() with attacker-controlled arguments.

        The How It Works section should describe the flow in user-facing terms
        ('the plugin contacts the VVUQ service') without exposing the function
        call syntax.
        """
        content = self._read_readme()
        # Match vvuq_resolve( in a descriptive prose context outside code fences
        # We scan line by line; code blocks in README use ``` delimiters
        in_code_block = False
        violations = []
        for line_num, line in enumerate(content.splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("```"):
                in_code_block = not in_code_block
            if not in_code_block and re.search(r'vvuq_resolve\s*\(', line):
                violations.append(
                    f"  README.md:{line_num}: {line.strip()[:120]}"
                )
        assert not violations, (
            "README.md exposes the internal MCP function call syntax 'vvuq_resolve()' "
            "in prose (outside a code fence).\n"
            "This gives prompt-injection attackers the exact function name to target.\n"
            "Violations:\n" + "\n".join(violations) + "\n"
            "Replace with user-facing language such as 'contacts the VVUQ service'."
        )


# ---------------------------------------------------------------------------
# 19. Round 3: External image loading in README (tracking vector)
# ---------------------------------------------------------------------------

class TestReadmeBadgeSecurity:
    """Verify that badge URLs in README.md do not introduce security or
    privacy risks beyond what is already accepted for the privacy.html file.

    The Round 3 README change adds three shields.io badge image URLs.
    shields.io is a well-known, legitimate service, but external image loads
    from a public README have two distinct risks:

    (a) Tracking: shields.io (or any CDN serving badge images) receives the
        viewer's IP address and User-Agent on each README render.  This is
        a weaker form of the tracking-pixel concern already tested in
        TestPrivacyHtmlSecurity.  Unlike privacy.html (served to end users),
        the README is typically rendered by GitHub's servers, which proxy the
        image requests.  However, if the README is ever rendered locally or
        via other clients, direct tracking is possible.

    (b) Version badge staleness as an integrity signal: the hardcoded
        ``version-0.1.0`` in the shields.io static badge URL will silently
        display an incorrect version after any release.  A user relying on
        the badge to verify they are installing the expected version receives
        false assurance -- a deceptive integrity indicator.

    (c) Badge URLs must use HTTPS and must not embed credentials or
        redirect through an attacker-controlled domain.

    Generated by: Security Critic Agent Round 3 (Claude Sonnet 4.6)
    Date: 2026-03-03
    """

    README_PATH = PLUGIN_ROOT / "README.md"

    def _read_readme(self) -> str:
        assert self.README_PATH.exists(), "README.md not found"
        return self.README_PATH.read_text(encoding="utf-8")

    def _extract_badge_image_urls(self) -> list[tuple[int, str]]:
        """Return (line_number, url) pairs for all Markdown image URLs in README."""
        content = self._read_readme()
        results = []
        # Matches ![alt](url) and [![alt](img_url)](link_url)
        img_url_pattern = re.compile(r'!\[[^\]]*\]\(([^)]+)\)')
        for line_num, line in enumerate(content.splitlines(), 1):
            for m in img_url_pattern.finditer(line):
                results.append((line_num, m.group(1).strip()))
        return results

    def test_badge_urls_use_https(self):
        """Rule: All badge image URLs in README.md must use HTTPS.

        HTTP badge URLs are vulnerable to MITM replacement: a network attacker
        can swap the badge image for one that signals a false status (e.g.,
        'build: passing' when tests actually fail) or inject tracking content.
        """
        badge_urls = self._extract_badge_image_urls()
        if not badge_urls:
            pytest.skip("No image URLs found in README.md")
        violations = []
        for line_num, url in badge_urls:
            if url.startswith("http://"):
                violations.append(f"  README.md:{line_num}: {url}")
        assert not violations, (
            "README.md badge URLs use insecure HTTP (MITM / status-spoofing risk):\n"
            + "\n".join(violations)
            + "\nAll badge image URLs must use HTTPS."
        )

    def test_badge_urls_do_not_embed_credentials(self):
        """Rule: Badge image URLs must not contain embedded credentials."""
        badge_urls = self._extract_badge_image_urls()
        if not badge_urls:
            pytest.skip("No image URLs found in README.md")
        violations = []
        for line_num, url in badge_urls:
            if re.search(r'://[^/]*:[^/]*@', url):
                violations.append(f"  README.md:{line_num}: {url}")
        assert not violations, (
            "README.md badge URLs contain embedded credentials:\n"
            + "\n".join(violations)
        )

    def test_badge_urls_use_known_domains(self):
        """Rule: Badge image URLs must come from a known, trusted CDN.

        An attacker who controls the badge URL domain can serve an image that
        tracks readers, loads malicious content in some renderers, or spoofs
        build status.  Only explicitly-allowlisted domains should be used for
        badge images.
        """
        ALLOWED_BADGE_DOMAINS = {
            "img.shields.io",          # shields.io static and dynamic badges
            "shields.io",              # shields.io redirects
            "github.com",             # GitHub Actions badge endpoint
            "raw.githubusercontent.com",  # GitHub raw assets
            "badgen.net",              # alternative badge service
            "codecov.io",             # coverage badges
        }
        badge_urls = self._extract_badge_image_urls()
        if not badge_urls:
            pytest.skip("No image URLs found in README.md")
        violations = []
        for line_num, url in badge_urls:
            # Extract domain
            m = re.match(r'https?://([^/]+)', url)
            if not m:
                violations.append(
                    f"  README.md:{line_num}: cannot parse domain from URL: {url}"
                )
                continue
            domain = m.group(1).lower()
            if domain not in ALLOWED_BADGE_DOMAINS:
                violations.append(
                    f"  README.md:{line_num}: badge served from unknown domain '{domain}': {url}"
                )
        assert not violations, (
            "README.md loads badge images from domains not in the allowlist.\n"
            "Unknown badge domains can track readers or spoof status:\n"
            + "\n".join(violations)
            + f"\nAllowed domains: {ALLOWED_BADGE_DOMAINS}"
        )

    def test_version_badge_matches_plugin_json(self):
        """Rule: The hardcoded version string in the shields.io static version badge
        must match the version declared in plugin.json.

        A stale version badge tells users they are running version X when they
        may actually be running version Y.  This is a false integrity signal:
        a user checking the badge to confirm they have the right version will
        receive incorrect information after any release.

        This test will fail as a reminder to update the badge whenever the
        version is bumped in plugin.json.
        """
        content = self._read_readme()
        plugin_path = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
        plugin_data = json.loads(plugin_path.read_text(encoding="utf-8"))
        plugin_version = plugin_data.get("version", "")
        assert plugin_version, "plugin.json does not declare a 'version' field"

        # Find the shields.io static badge URL containing a version string
        # Pattern: img.shields.io/badge/version-X.Y.Z-color.svg
        version_badge_pattern = re.compile(
            r'img\.shields\.io/badge/[^"\')\s]*version[^"\')\s]*-([0-9]+\.[0-9]+\.[0-9]+)-',
            re.IGNORECASE,
        )
        match = version_badge_pattern.search(content)
        if not match:
            pytest.xfail(
                "No shields.io static version badge found in README.md -- "
                "cannot verify version consistency.  If a dynamic badge is used "
                "this check can be removed."
            )

        badge_version = match.group(1)
        assert badge_version == plugin_version, (
            f"README.md version badge shows '{badge_version}' but plugin.json "
            f"declares version '{plugin_version}'.\n"
            "The badge version is hardcoded and must be updated on every release. "
            "Users relying on the badge to verify their installed version will "
            "receive false assurance after a version bump."
        )
