"""
Architecture violation tests for the VVUQ4AI Claude Code plugin.

Generated by: Architecture Critic Agent
Date: 2026-03-02

Each test reads the actual plugin files, parses JSON where needed,
and asserts structural correctness. Tests PASS if no violation found,
FAIL with a descriptive message if a violation is detected.
"""

import json
import re
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

PLUGIN_ROOT = Path(__file__).resolve().parent.parent.parent
"""Absolute path to the plugin root (vvuq4ai-plugin/)."""


def _read_json(relpath: str) -> dict:
    """Read and parse a JSON file relative to plugin root."""
    p = PLUGIN_ROOT / relpath
    assert p.exists(), f"Expected file not found: {p}"
    return json.loads(p.read_text())


def _read_text(relpath: str) -> str:
    """Read a text file relative to plugin root."""
    p = PLUGIN_ROOT / relpath
    assert p.exists(), f"Expected file not found: {p}"
    return p.read_text()


def _parse_frontmatter(text: str) -> dict:
    """
    Parse YAML-style frontmatter delimited by '---' lines.
    Returns a dict of key-value pairs (simple string values only for
    top-level scalar fields; multi-line values are kept as strings).
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    end_idx = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end_idx = i
            break
    if end_idx is None:
        return {}

    # Minimal YAML-like parsing (handles name: value and name: >)
    fm: dict = {}
    current_key = None
    current_val_lines: list[str] = []

    for line in lines[1:end_idx]:
        # Check for a new key
        m = re.match(r"^(\w[\w-]*):\s*(.*)", line)
        if m:
            # Flush previous key
            if current_key is not None:
                fm[current_key] = "\n".join(current_val_lines).strip()
            current_key = m.group(1)
            val = m.group(2).strip()
            if val == ">" or val == "|":
                current_val_lines = []
            elif val.startswith("[") or val.startswith("{"):
                # Inline list/dict -- keep raw
                current_val_lines = [val]
            elif val == "":
                current_val_lines = []
            else:
                current_val_lines = [val]
        elif current_key is not None:
            # Continuation line
            current_val_lines.append(line.strip())

    # Flush last key
    if current_key is not None:
        fm[current_key] = "\n".join(current_val_lines).strip()

    return fm


# ---------------------------------------------------------------------------
# 1. Required files exist
# ---------------------------------------------------------------------------


class TestRequiredFilesExist:
    """Every file listed in the plugin spec must physically exist."""

    REQUIRED_FILES = [
        ".claude-plugin/plugin.json",
        ".claude-plugin/marketplace.json",
        ".mcp.json",
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
        "README.md",
        "LICENSE",
        ".gitignore",
    ]

    @pytest.mark.parametrize("relpath", REQUIRED_FILES)
    def test_file_exists(self, relpath: str):
        p = PLUGIN_ROOT / relpath
        assert p.is_file(), f"Missing required file: {relpath}"


# ---------------------------------------------------------------------------
# 2. plugin.json validity
# ---------------------------------------------------------------------------


class TestPluginJson:
    """Validate .claude-plugin/plugin.json structure and content."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.data = _read_json(".claude-plugin/plugin.json")

    def test_required_fields_present(self):
        required = ["name", "version", "description", "author", "license"]
        for field in required:
            assert field in self.data, f"plugin.json missing required field: {field}"

    def test_name_is_lowercase_slug(self):
        name = self.data["name"]
        assert re.fullmatch(r"[a-z0-9][a-z0-9-]*", name), (
            f"plugin.json name '{name}' is not a valid lowercase slug"
        )

    def test_version_is_semver(self):
        version = self.data["version"]
        assert re.fullmatch(r"\d+\.\d+\.\d+", version), (
            f"plugin.json version '{version}' is not valid semver (X.Y.Z)"
        )

    def test_author_has_name(self):
        author = self.data.get("author", {})
        assert "name" in author, "plugin.json author missing 'name'"

    def test_mcp_servers_path_exists(self):
        mcp_path = self.data.get("mcpServers")
        assert mcp_path is not None, "plugin.json missing mcpServers field"
        # Resolve relative to plugin root
        resolved = PLUGIN_ROOT / mcp_path
        assert resolved.is_file(), (
            f"plugin.json mcpServers points to '{mcp_path}' but {resolved} does not exist"
        )


# ---------------------------------------------------------------------------
# 3. marketplace.json validity
# ---------------------------------------------------------------------------


class TestMarketplaceJson:
    """Validate .claude-plugin/marketplace.json structure and content."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.data = _read_json(".claude-plugin/marketplace.json")

    def test_required_top_level_fields(self):
        for field in ["name", "owner", "metadata", "plugins"]:
            assert field in self.data, f"marketplace.json missing field: {field}"

    def test_plugins_is_nonempty_list(self):
        plugins = self.data.get("plugins", [])
        assert isinstance(plugins, list), "marketplace.json plugins must be a list"
        assert len(plugins) > 0, "marketplace.json plugins list is empty"

    def test_each_plugin_has_required_fields(self):
        required = ["name", "source", "description", "version"]
        for i, plugin in enumerate(self.data.get("plugins", [])):
            for field in required:
                assert field in plugin, (
                    f"marketplace.json plugins[{i}] missing field: {field}"
                )


# ---------------------------------------------------------------------------
# 4. Version consistency across files
# ---------------------------------------------------------------------------


class TestVersionConsistency:
    """Version strings must match across plugin.json, marketplace.json, and SKILL.md."""

    def test_plugin_and_marketplace_versions_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_version = plugin["version"]
        marketplace_meta_version = marketplace["metadata"]["version"]
        assert plugin_version == marketplace_meta_version, (
            f"plugin.json version ({plugin_version}) != "
            f"marketplace.json metadata.version ({marketplace_meta_version})"
        )

    def test_plugin_and_marketplace_plugin_entry_versions_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_version = plugin["version"]
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_version = entry.get("version")
            assert plugin_version == entry_version, (
                f"plugin.json version ({plugin_version}) != "
                f"marketplace.json plugins[{i}].version ({entry_version})"
            )

    def test_skill_version_matches_plugin(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        skill_text = _read_text("skills/verify-claim/SKILL.md")
        fm = _parse_frontmatter(skill_text)

        skill_version = fm.get("version")
        if skill_version is not None:
            assert plugin["version"] == skill_version, (
                f"plugin.json version ({plugin['version']}) != "
                f"SKILL.md version ({skill_version})"
            )


# ---------------------------------------------------------------------------
# 5. Naming consistency
# ---------------------------------------------------------------------------


class TestNamingConsistency:
    """Plugin name must be consistent across all configuration files."""

    def test_plugin_and_marketplace_top_level_name_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        assert plugin["name"] == marketplace["name"], (
            f"plugin.json name ({plugin['name']}) != "
            f"marketplace.json name ({marketplace['name']})"
        )

    def test_plugin_and_marketplace_plugin_entry_name_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        for i, entry in enumerate(marketplace.get("plugins", [])):
            assert plugin["name"] == entry["name"], (
                f"plugin.json name ({plugin['name']}) != "
                f"marketplace.json plugins[{i}].name ({entry['name']})"
            )

    def test_mcp_server_key_matches_plugin_name(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        mcp = _read_json(".mcp.json")

        servers = mcp.get("mcpServers", {})
        assert plugin["name"] in servers, (
            f"MCP server key should be '{plugin['name']}' but .mcp.json has keys: "
            f"{list(servers.keys())}"
        )


# ---------------------------------------------------------------------------
# 6. Repository URL consistency
# ---------------------------------------------------------------------------


class TestRepositoryUrlConsistency:
    """
    Repository URLs in plugin.json and marketplace.json must point to
    the same repo. This is a known violation: plugin.json says
    dirkenglund/vvuq-mcp while marketplace.json says
    dirkenglund/vvuq4ai-plugin.
    """

    def test_repository_urls_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_repo = plugin.get("repository", "")
        # marketplace may have repo at top level or in plugins[] entries
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_repo = entry.get("repository", "")
            if plugin_repo and entry_repo:
                assert plugin_repo == entry_repo, (
                    f"REPOSITORY URL MISMATCH: "
                    f"plugin.json repository ({plugin_repo}) != "
                    f"marketplace.json plugins[{i}].repository ({entry_repo}). "
                    f"These must point to the same GitHub repo."
                )


# ---------------------------------------------------------------------------
# 7. MCP server configuration
# ---------------------------------------------------------------------------


class TestMcpServerConfig:
    """Validate .mcp.json structure and endpoint."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.data = _read_json(".mcp.json")

    def test_mcp_servers_key_exists(self):
        assert "mcpServers" in self.data, ".mcp.json missing 'mcpServers' key"

    def test_at_least_one_server_defined(self):
        servers = self.data.get("mcpServers", {})
        assert len(servers) > 0, ".mcp.json has no MCP servers defined"

    def test_each_server_has_url(self):
        for name, config in self.data.get("mcpServers", {}).items():
            assert "url" in config, (
                f"MCP server '{name}' in .mcp.json is missing 'url' field"
            )

    def test_server_url_is_https(self):
        for name, config in self.data.get("mcpServers", {}).items():
            url = config.get("url", "")
            assert url.startswith("https://"), (
                f"MCP server '{name}' URL must use HTTPS, got: {url}"
            )

    def test_server_url_has_trailing_slash(self):
        """
        The VVUQ MCP SSE endpoint requires a trailing slash.
        This is documented in the project memory and is a known gotcha.
        """
        for name, config in self.data.get("mcpServers", {}).items():
            url = config.get("url", "")
            assert url.endswith("/"), (
                f"MCP server '{name}' URL must end with trailing slash "
                f"(SSE endpoint requires it), got: {url}"
            )


# ---------------------------------------------------------------------------
# 8. Command frontmatter completeness
# ---------------------------------------------------------------------------


class TestCommandFrontmatter:
    """commands/verify.md must have all required frontmatter fields."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.text = _read_text("commands/verify.md")
        self.fm = _parse_frontmatter(self.text)

    def test_has_frontmatter(self):
        assert len(self.fm) > 0, "commands/verify.md has no frontmatter"

    def test_has_name(self):
        assert "name" in self.fm, "commands/verify.md frontmatter missing 'name'"

    def test_has_description(self):
        assert "description" in self.fm, (
            "commands/verify.md frontmatter missing 'description'"
        )

    def test_has_argument_hint(self):
        assert "argument-hint" in self.fm, (
            "commands/verify.md frontmatter missing 'argument-hint'"
        )

    def test_command_name_is_simple_slug(self):
        name = self.fm.get("name", "")
        assert re.fullmatch(r"[a-z][a-z0-9-]*", name), (
            f"Command name '{name}' is not a valid slug (lowercase, alphanumeric, hyphens)"
        )


# ---------------------------------------------------------------------------
# 9. Agent frontmatter completeness
# ---------------------------------------------------------------------------


class TestAgentFrontmatter:
    """agents/vvuq-verifier.md must have all required frontmatter fields."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.text = _read_text("agents/vvuq-verifier.md")
        self.fm = _parse_frontmatter(self.text)

    def test_has_frontmatter(self):
        assert len(self.fm) > 0, "agents/vvuq-verifier.md has no frontmatter"

    def test_has_name(self):
        assert "name" in self.fm, "agents/vvuq-verifier.md frontmatter missing 'name'"

    def test_has_description(self):
        assert "description" in self.fm, (
            "agents/vvuq-verifier.md frontmatter missing 'description'"
        )

    def test_name_matches_filename(self):
        """Agent name in frontmatter should match the filename (without .md)."""
        name = self.fm.get("name", "")
        filename_stem = Path("agents/vvuq-verifier.md").stem
        assert name == filename_stem, (
            f"Agent frontmatter name '{name}' does not match filename stem "
            f"'{filename_stem}'"
        )


# ---------------------------------------------------------------------------
# 10. Skill frontmatter completeness
# ---------------------------------------------------------------------------


class TestSkillFrontmatter:
    """skills/verify-claim/SKILL.md must have all required frontmatter fields."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.text = _read_text("skills/verify-claim/SKILL.md")
        self.fm = _parse_frontmatter(self.text)

    def test_has_frontmatter(self):
        assert len(self.fm) > 0, "SKILL.md has no frontmatter"

    def test_has_name(self):
        assert "name" in self.fm, "SKILL.md frontmatter missing 'name'"

    def test_has_description(self):
        assert "description" in self.fm, "SKILL.md frontmatter missing 'description'"

    def test_has_version(self):
        assert "version" in self.fm, "SKILL.md frontmatter missing 'version'"

    def test_skill_name_matches_directory(self):
        """Skill name in frontmatter should match the directory name."""
        name = self.fm.get("name", "")
        dir_name = "verify-claim"
        assert name == dir_name, (
            f"Skill frontmatter name '{name}' does not match directory "
            f"name '{dir_name}'"
        )


# ---------------------------------------------------------------------------
# 11. MCP tool references are consistent
# ---------------------------------------------------------------------------


class TestMcpToolReferences:
    """
    All tool names referenced in commands, agents, and skills must be
    consistent (same tool names everywhere).
    """

    TOOL_PATTERN = re.compile(r"`(vvuq_\w+)`")

    def _extract_tool_refs(self, relpath: str) -> set[str]:
        text = _read_text(relpath)
        return set(self.TOOL_PATTERN.findall(text))

    def test_command_references_vvuq_resolve(self):
        tools = self._extract_tool_refs("commands/verify.md")
        assert "vvuq_resolve" in tools, (
            f"commands/verify.md should reference vvuq_resolve tool. "
            f"Found references: {tools}"
        )

    def test_agent_references_vvuq_resolve(self):
        tools = self._extract_tool_refs("agents/vvuq-verifier.md")
        assert "vvuq_resolve" in tools, (
            f"agents/vvuq-verifier.md should reference vvuq_resolve tool. "
            f"Found references: {tools}"
        )

    def test_skill_references_vvuq_resolve(self):
        tools = self._extract_tool_refs("skills/verify-claim/SKILL.md")
        assert "vvuq_resolve" in tools, (
            f"skills/verify-claim/SKILL.md should reference vvuq_resolve tool. "
            f"Found references: {tools}"
        )

    def test_all_referenced_tools_are_from_same_set(self):
        """All tool references across all files should use the same tool names."""
        command_tools = self._extract_tool_refs("commands/verify.md")
        agent_tools = self._extract_tool_refs("agents/vvuq-verifier.md")
        skill_tools = self._extract_tool_refs("skills/verify-claim/SKILL.md")

        all_tools = command_tools | agent_tools | skill_tools
        # vvuq_resolve should be referenced everywhere that references tools
        for tools, source in [
            (command_tools, "commands/verify.md"),
            (agent_tools, "agents/vvuq-verifier.md"),
            (skill_tools, "skills/verify-claim/SKILL.md"),
        ]:
            unknown = tools - all_tools
            assert len(unknown) == 0, (
                f"{source} references unknown tools: {unknown}"
            )

    def test_agent_extra_tools_documented(self):
        """
        Agent references vvuq_query which is not mentioned in the command or skill.
        This is acceptable (agent is more capable) but the tool must be real.
        """
        agent_tools = self._extract_tool_refs("agents/vvuq-verifier.md")
        command_tools = self._extract_tool_refs("commands/verify.md")
        skill_tools = self._extract_tool_refs("skills/verify-claim/SKILL.md")

        agent_only = agent_tools - command_tools - skill_tools
        # Document what the agent exclusively references
        # This is informational -- the test passes but logs the difference
        if agent_only:
            # These tools are only referenced in the agent, not in command/skill.
            # This is fine architecturally but worth noting.
            pass
        # The real check: vvuq_query is referenced in the agent
        assert "vvuq_query" in agent_tools, (
            "Agent should reference vvuq_query for detailed topic lookups"
        )


# ---------------------------------------------------------------------------
# 12. Description consistency
# ---------------------------------------------------------------------------


class TestDescriptionConsistency:
    """Descriptions across files should be compatible (not contradictory)."""

    def test_plugin_and_marketplace_descriptions_compatible(self):
        """
        The core meaning should match even if the exact text differs.
        At minimum, if one has a prefix like 'VVUQ4AI -- ' the other
        should either have the same prefix or the non-prefixed version.
        """
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_desc = plugin["description"]
        market_desc = marketplace["metadata"]["description"]

        # These should be identical (they currently are)
        assert plugin_desc == market_desc, (
            f"plugin.json description and marketplace.json metadata.description "
            f"should be identical.\n"
            f"  plugin.json:      {plugin_desc!r}\n"
            f"  marketplace.json: {market_desc!r}"
        )

    def test_marketplace_plugin_entry_description_is_subset(self):
        """
        marketplace.json plugins[].description may be a shorter version
        but should not contradict the main description.
        """
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_desc = plugin["description"]
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_desc = entry.get("description", "")
            # The entry description should be contained within the full
            # description, or they should share key terms.
            key_terms = ["verify", "STEM", "claims"]
            for term in key_terms:
                assert term.lower() in entry_desc.lower(), (
                    f"marketplace.json plugins[{i}].description missing "
                    f"key term '{term}': {entry_desc!r}"
                )


# ---------------------------------------------------------------------------
# 13. License consistency
# ---------------------------------------------------------------------------


class TestLicenseConsistency:
    """License field in JSON files should match the LICENSE file."""

    def test_plugin_json_license_matches_license_file(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        license_text = _read_text("LICENSE")

        plugin_license = plugin.get("license", "")
        # The LICENSE file should contain the license type mentioned in plugin.json
        assert plugin_license.upper() in license_text.upper(), (
            f"plugin.json license is '{plugin_license}' but LICENSE file "
            f"does not contain that string"
        )

    def test_marketplace_plugin_license_matches(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        for i, entry in enumerate(marketplace.get("plugins", [])):
            if "license" in entry:
                assert entry["license"] == plugin["license"], (
                    f"marketplace.json plugins[{i}].license ({entry['license']}) != "
                    f"plugin.json license ({plugin['license']})"
                )


# ---------------------------------------------------------------------------
# 14. No dead file references
# ---------------------------------------------------------------------------


class TestNoDeadFileReferences:
    """
    References to local files (like ./.mcp.json or ./) must resolve to
    actual paths within the plugin directory.
    """

    def test_plugin_json_mcp_servers_path_resolves(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        mcp_path = plugin.get("mcpServers", "")
        resolved = (PLUGIN_ROOT / mcp_path).resolve()
        assert resolved.exists(), (
            f"plugin.json mcpServers path '{mcp_path}' does not resolve to a file: "
            f"{resolved}"
        )

    def test_marketplace_plugin_source_path_resolves(self):
        marketplace = _read_json(".claude-plugin/marketplace.json")
        for i, entry in enumerate(marketplace.get("plugins", [])):
            source = entry.get("source", "")
            resolved = (PLUGIN_ROOT / source).resolve()
            assert resolved.exists(), (
                f"marketplace.json plugins[{i}].source '{source}' does not resolve: "
                f"{resolved}"
            )

    def test_hooks_directory_not_empty_if_present(self):
        """
        If a hooks/ directory exists, it should contain actual hook scripts.
        An empty hooks directory is misleading.
        """
        hooks_dir = PLUGIN_ROOT / "hooks"
        if hooks_dir.is_dir():
            scripts_dir = hooks_dir / "scripts"
            if scripts_dir.is_dir():
                scripts = list(scripts_dir.iterdir())
                # Filter out hidden files like .DS_Store
                scripts = [s for s in scripts if not s.name.startswith(".")]
                assert len(scripts) > 0, (
                    "hooks/scripts/ directory exists but is empty. "
                    "Either add hook scripts or remove the directory."
                )


# ---------------------------------------------------------------------------
# 15. Keywords consistency
# ---------------------------------------------------------------------------


class TestKeywordsConsistency:
    """Keywords in plugin.json and marketplace.json should be consistent."""

    def test_keywords_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_kw = set(plugin.get("keywords", []))
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_kw = set(entry.get("keywords", []))
            if entry_kw:
                assert plugin_kw == entry_kw, (
                    f"Keywords mismatch between plugin.json and "
                    f"marketplace.json plugins[{i}].\n"
                    f"  plugin.json:      {sorted(plugin_kw)}\n"
                    f"  marketplace.json: {sorted(entry_kw)}"
                )


# ---------------------------------------------------------------------------
# 16. Author/owner consistency
# ---------------------------------------------------------------------------


class TestAuthorConsistency:
    """Author info in plugin.json should match owner in marketplace.json."""

    def test_author_name_matches_owner(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_author = plugin.get("author", {}).get("name", "")
        market_owner = marketplace.get("owner", {}).get("name", "")

        assert plugin_author == market_owner, (
            f"plugin.json author.name ({plugin_author!r}) != "
            f"marketplace.json owner.name ({market_owner!r})"
        )

    def test_author_email_matches_owner(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_email = plugin.get("author", {}).get("email", "")
        market_email = marketplace.get("owner", {}).get("email", "")

        assert plugin_email == market_email, (
            f"plugin.json author.email ({plugin_email!r}) != "
            f"marketplace.json owner.email ({market_email!r})"
        )


# ---------------------------------------------------------------------------
# 17. Homepage consistency
# ---------------------------------------------------------------------------


class TestHomepageConsistency:
    """Homepage URL should be consistent across files."""

    def test_homepage_matches(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_hp = plugin.get("homepage", "")
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_hp = entry.get("homepage", "")
            if plugin_hp and entry_hp:
                assert plugin_hp == entry_hp, (
                    f"plugin.json homepage ({plugin_hp}) != "
                    f"marketplace.json plugins[{i}].homepage ({entry_hp})"
                )


# ---------------------------------------------------------------------------
# 18. MCP endpoint in README matches .mcp.json
# ---------------------------------------------------------------------------


class TestReadmeEndpointConsistency:
    """README.md should reference the same MCP endpoint as .mcp.json."""

    def test_readme_mentions_mcp_url(self):
        mcp = _read_json(".mcp.json")
        readme = _read_text("README.md")

        for name, config in mcp.get("mcpServers", {}).items():
            url = config.get("url", "")
            assert url in readme, (
                f"README.md does not mention MCP server URL '{url}' "
                f"(server: {name})"
            )


# ---------------------------------------------------------------------------
# 19. No placeholder/TODO content in shipped files
# ---------------------------------------------------------------------------


class TestNoPlaceholderContent:
    """Shipped plugin files should not contain TODO, FIXME, or placeholder text."""

    FILES_TO_CHECK = [
        ".claude-plugin/plugin.json",
        ".claude-plugin/marketplace.json",
        ".mcp.json",
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
        "README.md",
    ]

    PLACEHOLDER_PATTERNS = [
        re.compile(r"\bTODO\b", re.IGNORECASE),
        re.compile(r"\bFIXME\b", re.IGNORECASE),
        re.compile(r"\bHACK\b", re.IGNORECASE),
        re.compile(r"\bXXX\b"),
        re.compile(r"<your[- ].*>", re.IGNORECASE),
        re.compile(r"example\.com"),
        re.compile(r"placeholder", re.IGNORECASE),
    ]

    @pytest.mark.parametrize("relpath", FILES_TO_CHECK)
    def test_no_placeholders(self, relpath: str):
        text = _read_text(relpath)
        for pattern in self.PLACEHOLDER_PATTERNS:
            matches = pattern.findall(text)
            assert len(matches) == 0, (
                f"{relpath} contains placeholder text matching "
                f"'{pattern.pattern}': {matches}"
            )


# ---------------------------------------------------------------------------
# 20. JSON files are valid JSON
# ---------------------------------------------------------------------------


class TestJsonValidity:
    """All JSON files must be parseable."""

    JSON_FILES = [
        ".claude-plugin/plugin.json",
        ".claude-plugin/marketplace.json",
        ".mcp.json",
    ]

    @pytest.mark.parametrize("relpath", JSON_FILES)
    def test_valid_json(self, relpath: str):
        p = PLUGIN_ROOT / relpath
        text = p.read_text()
        try:
            json.loads(text)
        except json.JSONDecodeError as e:
            pytest.fail(f"{relpath} is not valid JSON: {e}")


# ---------------------------------------------------------------------------
# 21. Frontmatter delimiter correctness
# ---------------------------------------------------------------------------


class TestFrontmatterDelimiters:
    """Markdown files with frontmatter must have proper --- delimiters."""

    MARKDOWN_FILES = [
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
    ]

    @pytest.mark.parametrize("relpath", MARKDOWN_FILES)
    def test_frontmatter_has_opening_and_closing_delimiters(self, relpath: str):
        text = _read_text(relpath)
        lines = text.split("\n")
        assert lines[0].strip() == "---", (
            f"{relpath} does not start with '---' frontmatter delimiter"
        )
        # Find closing delimiter (must be after line 0)
        closing_found = False
        for line in lines[1:]:
            if line.strip() == "---":
                closing_found = True
                break
        assert closing_found, (
            f"{relpath} is missing closing '---' frontmatter delimiter"
        )


# ---------------------------------------------------------------------------
# 22. Server-side assets must not ship in the plugin distribution
# ---------------------------------------------------------------------------


class TestNoServerSideAssets:
    """
    A Claude Code plugin is a client-side artifact: JSON configs, markdown
    instructions, and a .mcp.json that points to a remote server. Files that
    belong to the MCP *server* (HTML pages, CSS, server configs, templates)
    violate separation of concerns and must not be distributed with the plugin.

    Architecture principle: Single Responsibility -- the plugin repo defines
    how the Claude client talks to the server; the server repo owns everything
    the server serves.

    Generated by: Architecture Critic Agent (Round 2)
    Date: 2026-03-03
    """

    # File types that are server-side assets, not plugin components.
    # Claude Code plugins consist of: JSON, markdown, and optionally
    # shell scripts (hooks). HTML, CSS, JS (frontend), and templates
    # are server-side concerns.
    SERVER_SIDE_EXTENSIONS = {".html", ".css", ".jsx", ".tsx", ".vue", ".svelte"}

    # Files that are legitimate even with the above extensions
    # (none expected, but structure allows exceptions)
    ALLOWED_EXCEPTIONS: set[str] = set()

    def test_no_html_files_in_plugin_root(self):
        """HTML files are server-side assets. A Claude Code plugin has no
        use for HTML -- it uses markdown for instructions and JSON for config.
        HTML files belong in the MCP server repo (dirkenglund/vvuq-mcp),
        not the plugin repo."""
        html_files = list(PLUGIN_ROOT.glob("*.html"))
        html_files = [f for f in html_files if f.name not in self.ALLOWED_EXCEPTIONS]
        assert len(html_files) == 0, (
            f"HTML file(s) found in plugin root: "
            f"{[f.name for f in html_files]}. "
            f"HTML pages are server-side assets and belong in the MCP server "
            f"repo (dirkenglund/vvuq-mcp), not the plugin distribution. "
            f"The plugin repo should only contain JSON configs, markdown "
            f"instructions, and optionally hook scripts."
        )

    def test_no_server_side_files_anywhere_in_tree(self):
        """Scan the entire plugin tree (excluding .git and tests) for
        server-side file types that should not be distributed."""
        skip_dirs = {".git", ".github", "__pycache__", ".pytest_cache", ".benchmarks", "tests"}
        violations = []
        for fpath in PLUGIN_ROOT.rglob("*"):
            if not fpath.is_file():
                continue
            if any(ex in fpath.parts for ex in skip_dirs):
                continue
            if fpath.name in self.ALLOWED_EXCEPTIONS:
                continue
            if fpath.suffix.lower() in self.SERVER_SIDE_EXTENSIONS:
                violations.append(str(fpath.relative_to(PLUGIN_ROOT)))

        assert violations == [], (
            f"Server-side asset(s) found in plugin distribution: {violations}. "
            f"These file types ({self.SERVER_SIDE_EXTENSIONS}) belong in the "
            f"MCP server repo, not the client-side plugin."
        )

    def test_privacy_html_not_in_plugin(self):
        """privacy.html is a web page served by the MCP server at
        https://vvuq.dirkenglund.org/privacy. It is a server-side
        concern and must not exist in the plugin repo.

        Correct location: dirkenglund/vvuq-mcp repo
        Plugin alternative: link to the hosted URL from README.md
        """
        privacy_path = PLUGIN_ROOT / "privacy.html"
        assert not privacy_path.exists(), (
            "privacy.html exists in the plugin repo. This is a server-side "
            "web page that should be hosted by the MCP server and served at "
            "https://vvuq.dirkenglund.org/privacy. Move it to the "
            "dirkenglund/vvuq-mcp repo and add a link to the hosted page "
            "in the plugin's README.md instead."
        )


# ---------------------------------------------------------------------------
# 23. Plugin distribution must only contain recognized file types
# ---------------------------------------------------------------------------


class TestDistributionFileTypes:
    """
    A Claude Code plugin distribution should contain only files that the
    plugin framework understands: JSON configs, markdown instructions,
    a LICENSE file, and a .gitignore. Any other file type is either a
    mistake or belongs in a different repo.

    Architecture principle: Interface Segregation -- the plugin interface
    should expose only what the framework consumes.
    """

    # File types that are legitimate in a Claude Code plugin distribution
    ALLOWED_EXTENSIONS = {".json", ".md", ".toml", ""}  # "" covers extensionless files like LICENSE
    ALLOWED_FILENAMES = {"LICENSE", ".gitignore"}

    def test_all_distribution_files_are_recognized_types(self):
        """Every file in the distribution (excluding tests, .git, caches)
        must be a recognized plugin file type."""
        skip_dirs = {".git", ".github", "__pycache__", ".pytest_cache", ".benchmarks", "tests"}
        unrecognized = []
        for fpath in PLUGIN_ROOT.rglob("*"):
            if not fpath.is_file():
                continue
            if any(ex in fpath.parts for ex in skip_dirs):
                continue
            if fpath.name in self.ALLOWED_FILENAMES:
                continue
            if fpath.suffix.lower() in self.ALLOWED_EXTENSIONS:
                continue
            unrecognized.append(
                f"{fpath.relative_to(PLUGIN_ROOT)} (type: {fpath.suffix})"
            )

        assert unrecognized == [], (
            f"Unrecognized file types in plugin distribution: {unrecognized}. "
            f"A Claude Code plugin should only contain: "
            f"JSON ({'.json'}), Markdown ({'.md'}), LICENSE, and .gitignore. "
            f"Other file types likely belong in a different repository."
        )


# ---------------------------------------------------------------------------
# 24. Privacy policy should be linked, not shipped
# ---------------------------------------------------------------------------


class TestPrivacyPolicyReference:
    """
    If the MCP server collects user data (which the existence of
    privacy.html confirms), the plugin's README should link to the
    hosted privacy policy so users can review it before use.

    Architecture principle: Dependency Inversion -- the plugin should
    depend on the server's published privacy URL, not embed the page.
    """

    def test_readme_links_to_privacy_policy(self):
        """README should contain a link to the privacy policy if the
        MCP service collects data (claim text, server logs)."""
        readme = _read_text("README.md")
        has_privacy_link = any(
            term in readme.lower()
            for term in [
                "privacy",
                "privacy policy",
                "data collection",
                "data handling",
            ]
        )
        # This test currently expects the README to mention privacy.
        # If the README already has it, great. If not, it should be added
        # since the MCP server collects claim text per the privacy policy.
        if not has_privacy_link:
            pytest.xfail(
                "README.md does not mention privacy or data collection. "
                "The MCP server collects claim text and server logs per its "
                "privacy policy. The plugin README should link to the hosted "
                "privacy policy at https://vvuq.dirkenglund.org/privacy so "
                "users know what data is collected before installing."
            )


# ---------------------------------------------------------------------------
# 25. Security scanner coverage gap -- HTML files
# ---------------------------------------------------------------------------


class TestSecurityScannerCoverage:
    """
    The security tests in test_security_violations.py define
    SCANNABLE_EXTENSIONS that determine which files are scanned for
    secrets, credentials, and internal infrastructure details. HTML
    files are NOT in that set, meaning any .html file would completely
    bypass security scanning.

    Architecture principle: Open/Closed -- the security scanner should
    be open to new file types without requiring modification to each
    individual test.
    """

    def test_all_text_files_are_scannable(self):
        """Every text file in the distribution should be covered by the
        security scanner's file type filter. Files that slip through
        could contain secrets, internal hostnames, or other sensitive
        data without detection."""
        # These are the extensions the security scanner covers
        security_scannable = {
            ".json", ".md", ".txt", ".yml", ".yaml", ".toml",
            ".cfg", ".ini", ".sh",
        }
        security_scannable_names = {".gitignore", "LICENSE"}

        skip_dirs = {".git", ".github", "__pycache__", ".pytest_cache", ".benchmarks", "tests"}
        uncovered = []
        for fpath in PLUGIN_ROOT.rglob("*"):
            if not fpath.is_file():
                continue
            if any(ex in fpath.parts for ex in skip_dirs):
                continue
            if fpath.name in security_scannable_names:
                continue
            if fpath.suffix.lower() in security_scannable:
                continue
            # This file would not be scanned by the security tests
            try:
                fpath.read_text(encoding="utf-8")
                # It is a text file that bypasses security scanning
                uncovered.append(
                    f"{fpath.relative_to(PLUGIN_ROOT)} (type: {fpath.suffix})"
                )
            except (UnicodeDecodeError, ValueError):
                # Binary file -- not relevant for text-based secret scanning
                continue

        assert uncovered == [], (
            f"Text files that bypass security scanning: {uncovered}. "
            f"The security scanner in test_security_violations.py only covers "
            f"these extensions: {sorted(security_scannable)}. "
            f"Any text file with a different extension can contain secrets, "
            f"internal hostnames, or credentials without being detected. "
            f"Either remove these files from the distribution or expand the "
            f"security scanner's SCANNABLE_EXTENSIONS."
        )


# ---------------------------------------------------------------------------
# 26. Plugin repo must not duplicate MCP server repo content
# ---------------------------------------------------------------------------


class TestNoMcpServerDuplication:
    """
    The VVUQ4AI system has two repos:
      - dirkenglund/vvuq4ai-plugin (this repo) -- client-side plugin
      - dirkenglund/vvuq-mcp (private) -- MCP server

    Files that implement server-side functionality (API endpoints,
    database schemas, web pages, server configs) must live exclusively
    in the server repo. Duplicating them here creates maintenance
    burden, version drift, and confusion about which copy is canonical.

    Architecture principle: Single source of truth.
    """

    # Patterns that indicate server-side content
    SERVER_CONTENT_INDICATORS = [
        # Web server configuration
        (re.compile(r"<html|<head|<body|<!DOCTYPE", re.IGNORECASE), "HTML document"),
        # Server-side templates (Jinja, EJS, etc.)
        (re.compile(r"\{\{.*\}\}|<%.*%>"), "Server template syntax"),
        # Nginx/Apache config
        (re.compile(r"server\s*\{|location\s*/|<VirtualHost"), "Web server config"),
        # Dockerfile / docker-compose
        (re.compile(r"^FROM\s+\w+|^services:\s*$", re.MULTILINE), "Docker config"),
        # systemd service files
        (re.compile(r"^\[Unit\]|^\[Service\]|^\[Install\]", re.MULTILINE), "systemd unit"),
    ]

    def test_no_server_content_in_distribution(self):
        """Scan all distribution files for patterns that indicate
        server-side content that belongs in the MCP server repo."""
        skip_dirs = {".git", ".github", "__pycache__", ".pytest_cache", ".benchmarks", "tests"}
        violations = []
        for fpath in PLUGIN_ROOT.rglob("*"):
            if not fpath.is_file():
                continue
            if any(ex in fpath.parts for ex in skip_dirs):
                continue
            try:
                content = fpath.read_text(encoding="utf-8")
            except (UnicodeDecodeError, ValueError):
                continue
            for pattern, description in self.SERVER_CONTENT_INDICATORS:
                if pattern.search(content):
                    violations.append(
                        f"{fpath.relative_to(PLUGIN_ROOT)}: "
                        f"contains {description}"
                    )
                    break  # One match per file is enough

        assert violations == [], (
            f"Server-side content found in plugin distribution:\n"
            + "\n".join(f"  {v}" for v in violations)
            + "\n\nThese files contain content that belongs in the MCP server "
            "repo (dirkenglund/vvuq-mcp), not the client-side plugin."
        )


# ---------------------------------------------------------------------------
# 27. .gitignore should exclude server-side file types
# ---------------------------------------------------------------------------


class TestGitignoreServerExclusions:
    """
    Since the plugin repo should not contain server-side assets,
    .gitignore should include patterns to prevent accidental commits
    of common server-side file types.
    """

    def test_gitignore_excludes_html(self):
        """HTML files are server-side assets that should not be committed
        to the plugin repo. .gitignore should have a pattern for them."""
        gitignore = _read_text(".gitignore")
        lines = [
            line.strip()
            for line in gitignore.splitlines()
            if line.strip() and not line.strip().startswith("#")
        ]
        has_html_exclusion = any(
            "*.html" in line or "privacy.html" in line
            for line in lines
        )
        assert has_html_exclusion, (
            ".gitignore does not exclude HTML files (*.html). "
            "Server-side web pages like privacy.html can be accidentally "
            "committed to the plugin repo. Add '*.html' to .gitignore."
        )


# ---------------------------------------------------------------------------
# 28. CI workflow structure (added Round 3)
# ---------------------------------------------------------------------------


class TestCiWorkflowStructure:
    """
    The CI workflow at .github/workflows/tests.yml was added in Round 3.
    Several structural deficiencies create reproducibility and reliability
    risks that are architectural in nature.

    Architecture principles addressed:
      - Open/Closed: CI should be robust to future dependency additions
        without manual intervention (missing requirements file).
      - Single Responsibility: each CI step should have a clear, bounded
        purpose; an unbounded step can consume shared runner resources.
      - Dependency Inversion: CI should depend on pinned abstractions
        (locked dependency versions), not on floating latest versions.

    Generated by: Architecture Critic Agent (Round 3)
    Date: 2026-03-03
    """

    CI_PATH = ".github/workflows/tests.yml"

    @pytest.fixture(autouse=True)
    def load(self):
        self.text = _read_text(self.CI_PATH)

    def test_ci_workflow_file_exists(self):
        """The CI workflow file must exist before any other CI checks are
        meaningful."""
        p = PLUGIN_ROOT / self.CI_PATH
        assert p.is_file(), f"CI workflow not found: {self.CI_PATH}"

    def test_ci_has_job_level_timeout(self):
        """
        CI jobs without a timeout-minutes cap can hang indefinitely on
        GitHub Actions, consuming runner minutes and blocking the queue.
        Every job must declare an explicit timeout.

        The global project guidelines (CLAUDE.md) also mandate a 30-second
        pytest timeout per test, reinforcing that unbounded execution is
        unacceptable at every level of the stack.

        Add 'timeout-minutes: 10' (or lower) to the job definition.
        """
        # Look for timeout-minutes at any indentation under jobs:
        has_timeout = bool(re.search(r"timeout-minutes\s*:", self.text))
        assert has_timeout, (
            f"{self.CI_PATH} has no 'timeout-minutes' on any job. "
            "A hanging test suite (e.g. infinite loop, deadlock, or "
            "network wait) will consume runner minutes indefinitely. "
            "Add 'timeout-minutes: 10' to the job definition. "
            "The global project guidelines also require a 30-second "
            "per-test timeout via [tool.pytest.ini_options] in "
            "pyproject.toml."
        )

    def test_ci_pins_pytest_version(self):
        """
        'pip install pytest' without a version pin installs the latest
        release at workflow execution time. A breaking change in pytest
        (new warning promoted to error, changed exit codes, removed API)
        can silently break CI on any push without any code change in this
        repo. Pins should be specified as 'pytest==X.Y.Z' or via a
        requirements file.

        Architecture principle: Dependency Inversion -- depend on fixed
        versions, not on whatever happens to be latest.
        """
        # Match any pip install line that mentions pytest without a pin
        # A pin looks like: pytest==X, pytest>=X,<Y, pytest~=X, etc.
        bare_pytest = re.search(
            r"pip install\b[^'\"\n]*\bpytest\b(?![-=<>!~])", self.text
        )
        assert bare_pytest is None, (
            f"{self.CI_PATH} installs pytest without a version pin. "
            "Non-pinned dependencies make CI non-reproducible: a new "
            "pytest release can break the test run without any change "
            "to this repository. "
            "Fix: use 'pytest==X.Y.Z' or create a requirements-test.txt "
            "and run 'pip install -r requirements-test.txt'."
        )

    def test_ci_or_repo_has_pytest_dependency_file(self):
        """
        The CI workflow installs pytest, but there is no pyproject.toml,
        setup.cfg, requirements.txt, or requirements-test.txt in the repo
        to record the test dependency. This means:
          1. The required pytest version is only documented in the CI YAML.
          2. A local developer has no machine-readable way to install the
             correct test environment.
          3. Adding a second test dependency requires editing the YAML
             rather than a standard dependency file.

        Architecture principle: Single Responsibility -- dependency
        declarations belong in a dependency file, not embedded in CI steps.

        Fix: add a pyproject.toml with [tool.pytest.ini_options] (also
        required by global project guidelines for the 'timeout = 30'
        setting) and list pytest as a dev dependency there.
        """
        dependency_files = [
            "pyproject.toml",
            "setup.cfg",
            "requirements.txt",
            "requirements-test.txt",
            "requirements-dev.txt",
        ]
        found = [f for f in dependency_files if (PLUGIN_ROOT / f).is_file()]
        assert found, (
            "No Python dependency file found in the plugin root. "
            f"Checked: {dependency_files}. "
            "The CI workflow installs pytest but the required version and "
            "any future test dependencies have no machine-readable home. "
            "Add a pyproject.toml with:\n"
            "  [tool.pytest.ini_options]\n"
            "  timeout = 30\n\n"
            "This also satisfies the global project requirement for a "
            "per-test timeout to prevent runaway memory consumption."
        )

    def test_ci_triggers_include_pull_request(self):
        """
        CI should run on both push and pull_request events. Running only
        on push means a PR with a broken test suite can be merged before
        CI catches the failure. Both triggers were present in the workflow
        as written, but this test enforces they stay present.
        """
        assert "pull_request" in self.text, (
            f"{self.CI_PATH} does not trigger on pull_request events. "
            "CI must run before merging, not only after. "
            "Add 'pull_request: branches: [main]' to the 'on:' block."
        )

    def test_ci_uses_checkout_action(self):
        """
        The workflow must check out the repository before running tests.
        actions/checkout is the standard action for this and must be
        present.
        """
        assert "actions/checkout" in self.text, (
            f"{self.CI_PATH} does not use actions/checkout. "
            "Without a checkout step the runner has no source files to test."
        )

    def test_ci_checkout_action_is_pinned_to_major_version(self):
        """
        GitHub Actions can be referenced by tag, branch, or SHA. Using
        '@v4' (major version) is the community standard that gives a
        balance between reproducibility and receiving security patches.
        'actions/checkout' without any version suffix is unsafe.
        """
        # Accept @v3, @v4, @vN or full SHA (40 hex chars)
        unpinned = re.search(
            r"uses:\s*actions/checkout(?!@)", self.text
        )
        assert unpinned is None, (
            f"{self.CI_PATH} references 'actions/checkout' without a "
            "version pin (e.g. '@v4'). Unpinned actions can change "
            "behavior without notice. Use 'actions/checkout@v4' or pin "
            "to a specific commit SHA."
        )


# ---------------------------------------------------------------------------
# 29. README badge structural correctness (added Round 3)
# ---------------------------------------------------------------------------


class TestReadmeBadgeStructure:
    """
    The README was rewritten in Round 3 with three badges. One badge
    links to the raw plugin.json file on GitHub, which is an unusual
    choice for a 'version' badge and creates a coupling between the
    README presentation layer and the internal JSON schema.

    Architecture principle: Interface Segregation -- the README is a
    public interface document; it should not hard-code links to internal
    implementation files as canonical version sources.

    Generated by: Architecture Critic Agent (Round 3)
    Date: 2026-03-03
    """

    def test_readme_has_badges_section(self):
        """README must contain at least one badge (already present, this
        test guards against accidental removal)."""
        readme = _read_text("README.md")
        has_badge = bool(re.search(r"!\[.*?\]\(https://img\.shields\.io", readme))
        assert has_badge, (
            "README.md contains no shields.io badges. "
            "The badges for License, CI status, and version were added "
            "in Round 3 and should be preserved."
        )

    def test_readme_ci_badge_references_correct_workflow_file(self):
        """
        The CI status badge URL must reference the actual workflow file
        name that exists at .github/workflows/tests.yml. A mismatch means
        the badge will always show 'no status' even when CI passes.

        This is an architecture issue: the README and the CI definition
        are coupled and must stay in sync.
        """
        readme = _read_text("README.md")
        # The badge should reference the workflow file by its filename
        workflow_filename = "tests.yml"
        # GitHub Actions badge URL pattern:
        # https://github.com/<owner>/<repo>/actions/workflows/<file>/badge.svg
        badge_pattern = re.compile(
            r"https://github\.com/[^/]+/[^/]+/actions/workflows/([^/\"')]+)/badge\.svg"
        )
        matches = badge_pattern.findall(readme)
        if not matches:
            # No CI badge at all
            pytest.fail(
                "README.md has no GitHub Actions CI badge. "
                "A CI badge provides immediate visibility into build health "
                "for potential users inspecting the repo."
            )
        for badge_workflow in matches:
            assert badge_workflow == workflow_filename, (
                f"README CI badge references workflow file '{badge_workflow}' "
                f"but the actual workflow file is '{workflow_filename}'. "
                "A mismatched filename causes the badge to show 'no status'. "
                "Update the badge URL to match the actual filename."
            )

    def test_readme_version_badge_does_not_link_to_internal_json(self):
        """
        The version badge currently links to '.claude-plugin/plugin.json'.
        Badges should link to public, stable, human-readable resources
        (release pages, changelogs, tags) rather than internal config files.
        Linking to plugin.json couples the public README to an internal
        schema file and sends curious users to raw JSON instead of a
        release page.

        Acceptable targets: GitHub releases page, CHANGELOG.md, a tag URL.
        Unacceptable: raw paths to internal JSON files.

        Architecture principle: Dependency Inversion -- the public README
        should depend on stable public release artifacts, not on internal
        implementation files.
        """
        readme = _read_text("README.md")
        # Find badge links that point to .claude-plugin/plugin.json
        internal_json_badge = re.search(
            r"!\[Version\]\(https://img\.shields\.io[^)]+\)\]\(\.claude-plugin/plugin\.json\)",
            readme,
        )
        if internal_json_badge:
            pytest.xfail(
                "README version badge links to '.claude-plugin/plugin.json'. "
                "This couples the public README to an internal config file and "
                "sends users to raw JSON instead of a release page. "
                "Consider linking to the GitHub releases page "
                "(https://github.com/dirkenglund/vvuq4ai-plugin/releases) "
                "or removing the version badge in favor of keeping the version "
                "solely in plugin.json (the canonical source). "
                "Using xfail because this is a minor UX issue, not a "
                "functional breakage."
            )


# ---------------------------------------------------------------------------
# 30. pyproject.toml with pytest timeout is required (added Round 3)
# ---------------------------------------------------------------------------


class TestPytestTimeoutConfiguration:
    """
    The global project guidelines (CLAUDE.md -- Test Safety & Resource Limits)
    mandate that all projects include a pytest timeout setting to prevent
    runaway test processes. The CI workflow (added Round 3) runs pytest
    with no timeout, compounding this gap.

    Architecture principle: Single Responsibility -- test configuration
    belongs in pyproject.toml, not scattered across CI YAML and ad-hoc
    conftest fixtures.

    Generated by: Architecture Critic Agent (Round 3)
    Date: 2026-03-03
    """

    def test_pyproject_toml_exists(self):
        """
        A pyproject.toml is the modern, PEP-compliant location for project
        metadata and tool configuration. Its absence means pytest settings,
        test dependencies, and tool configuration have no standard home.
        This test will fail until pyproject.toml is created.
        """
        p = PLUGIN_ROOT / "pyproject.toml"
        if not p.exists():
            pytest.xfail(
                "pyproject.toml does not exist. "
                "Create it with at minimum:\n\n"
                "  [tool.pytest.ini_options]\n"
                "  timeout = 30\n\n"
                "The global project guidelines (CLAUDE.md) require a "
                "'timeout = 30' setting to prevent runaway test processes. "
                "Without this, the CI workflow added in Round 3 can hang "
                "indefinitely if a test enters an infinite loop or blocks "
                "on a network call."
            )

    def test_pytest_timeout_configured(self):
        """
        If pyproject.toml exists, it must declare a pytest timeout.
        A missing timeout means a single blocking test (network I/O,
        infinite loop) can hang the entire CI run.
        """
        p = PLUGIN_ROOT / "pyproject.toml"
        if not p.exists():
            pytest.skip("pyproject.toml does not exist (covered by test_pyproject_toml_exists)")

        content = p.read_text(encoding="utf-8")
        has_timeout = bool(re.search(r"timeout\s*=\s*\d+", content))
        assert has_timeout, (
            "pyproject.toml exists but does not set a pytest timeout. "
            "Add to [tool.pytest.ini_options]:\n"
            "  timeout = 30\n\n"
            "This prevents any single test from hanging the CI runner."
        )
