"""
Architecture violation tests for the VVUQ4AI Claude Code plugin.

Generated by: Architecture Critic Agent
Date: 2026-03-02

Each test reads the actual plugin files, parses JSON where needed,
and asserts structural correctness. Tests PASS if no violation found,
FAIL with a descriptive message if a violation is detected.
"""

import json
import re
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

PLUGIN_ROOT = Path(__file__).resolve().parent.parent.parent
"""Absolute path to the plugin root (vvuq4ai-plugin/)."""


def _read_json(relpath: str) -> dict:
    """Read and parse a JSON file relative to plugin root."""
    p = PLUGIN_ROOT / relpath
    assert p.exists(), f"Expected file not found: {p}"
    return json.loads(p.read_text())


def _read_text(relpath: str) -> str:
    """Read a text file relative to plugin root."""
    p = PLUGIN_ROOT / relpath
    assert p.exists(), f"Expected file not found: {p}"
    return p.read_text()


def _parse_frontmatter(text: str) -> dict:
    """
    Parse YAML-style frontmatter delimited by '---' lines.
    Returns a dict of key-value pairs (simple string values only for
    top-level scalar fields; multi-line values are kept as strings).
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    end_idx = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end_idx = i
            break
    if end_idx is None:
        return {}

    # Minimal YAML-like parsing (handles name: value and name: >)
    fm: dict = {}
    current_key = None
    current_val_lines: list[str] = []

    for line in lines[1:end_idx]:
        # Check for a new key
        m = re.match(r"^(\w[\w-]*):\s*(.*)", line)
        if m:
            # Flush previous key
            if current_key is not None:
                fm[current_key] = "\n".join(current_val_lines).strip()
            current_key = m.group(1)
            val = m.group(2).strip()
            if val == ">" or val == "|":
                current_val_lines = []
            elif val.startswith("[") or val.startswith("{"):
                # Inline list/dict -- keep raw
                current_val_lines = [val]
            elif val == "":
                current_val_lines = []
            else:
                current_val_lines = [val]
        elif current_key is not None:
            # Continuation line
            current_val_lines.append(line.strip())

    # Flush last key
    if current_key is not None:
        fm[current_key] = "\n".join(current_val_lines).strip()

    return fm


# ---------------------------------------------------------------------------
# 1. Required files exist
# ---------------------------------------------------------------------------


class TestRequiredFilesExist:
    """Every file listed in the plugin spec must physically exist."""

    REQUIRED_FILES = [
        ".claude-plugin/plugin.json",
        ".claude-plugin/marketplace.json",
        ".mcp.json",
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
        "README.md",
        "LICENSE",
        ".gitignore",
    ]

    @pytest.mark.parametrize("relpath", REQUIRED_FILES)
    def test_file_exists(self, relpath: str):
        p = PLUGIN_ROOT / relpath
        assert p.is_file(), f"Missing required file: {relpath}"


# ---------------------------------------------------------------------------
# 2. plugin.json validity
# ---------------------------------------------------------------------------


class TestPluginJson:
    """Validate .claude-plugin/plugin.json structure and content."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.data = _read_json(".claude-plugin/plugin.json")

    def test_required_fields_present(self):
        required = ["name", "version", "description", "author", "license"]
        for field in required:
            assert field in self.data, f"plugin.json missing required field: {field}"

    def test_name_is_lowercase_slug(self):
        name = self.data["name"]
        assert re.fullmatch(r"[a-z0-9][a-z0-9-]*", name), (
            f"plugin.json name '{name}' is not a valid lowercase slug"
        )

    def test_version_is_semver(self):
        version = self.data["version"]
        assert re.fullmatch(r"\d+\.\d+\.\d+", version), (
            f"plugin.json version '{version}' is not valid semver (X.Y.Z)"
        )

    def test_author_has_name(self):
        author = self.data.get("author", {})
        assert "name" in author, "plugin.json author missing 'name'"

    def test_mcp_servers_path_exists(self):
        mcp_path = self.data.get("mcpServers")
        assert mcp_path is not None, "plugin.json missing mcpServers field"
        # Resolve relative to plugin root
        resolved = PLUGIN_ROOT / mcp_path
        assert resolved.is_file(), (
            f"plugin.json mcpServers points to '{mcp_path}' but {resolved} does not exist"
        )


# ---------------------------------------------------------------------------
# 3. marketplace.json validity
# ---------------------------------------------------------------------------


class TestMarketplaceJson:
    """Validate .claude-plugin/marketplace.json structure and content."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.data = _read_json(".claude-plugin/marketplace.json")

    def test_required_top_level_fields(self):
        for field in ["name", "owner", "metadata", "plugins"]:
            assert field in self.data, f"marketplace.json missing field: {field}"

    def test_plugins_is_nonempty_list(self):
        plugins = self.data.get("plugins", [])
        assert isinstance(plugins, list), "marketplace.json plugins must be a list"
        assert len(plugins) > 0, "marketplace.json plugins list is empty"

    def test_each_plugin_has_required_fields(self):
        required = ["name", "source", "description", "version"]
        for i, plugin in enumerate(self.data.get("plugins", [])):
            for field in required:
                assert field in plugin, (
                    f"marketplace.json plugins[{i}] missing field: {field}"
                )


# ---------------------------------------------------------------------------
# 4. Version consistency across files
# ---------------------------------------------------------------------------


class TestVersionConsistency:
    """Version strings must match across plugin.json, marketplace.json, and SKILL.md."""

    def test_plugin_and_marketplace_versions_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_version = plugin["version"]
        marketplace_meta_version = marketplace["metadata"]["version"]
        assert plugin_version == marketplace_meta_version, (
            f"plugin.json version ({plugin_version}) != "
            f"marketplace.json metadata.version ({marketplace_meta_version})"
        )

    def test_plugin_and_marketplace_plugin_entry_versions_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_version = plugin["version"]
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_version = entry.get("version")
            assert plugin_version == entry_version, (
                f"plugin.json version ({plugin_version}) != "
                f"marketplace.json plugins[{i}].version ({entry_version})"
            )

    def test_skill_version_matches_plugin(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        skill_text = _read_text("skills/verify-claim/SKILL.md")
        fm = _parse_frontmatter(skill_text)

        skill_version = fm.get("version")
        if skill_version is not None:
            assert plugin["version"] == skill_version, (
                f"plugin.json version ({plugin['version']}) != "
                f"SKILL.md version ({skill_version})"
            )


# ---------------------------------------------------------------------------
# 5. Naming consistency
# ---------------------------------------------------------------------------


class TestNamingConsistency:
    """Plugin name must be consistent across all configuration files."""

    def test_plugin_and_marketplace_top_level_name_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        assert plugin["name"] == marketplace["name"], (
            f"plugin.json name ({plugin['name']}) != "
            f"marketplace.json name ({marketplace['name']})"
        )

    def test_plugin_and_marketplace_plugin_entry_name_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        for i, entry in enumerate(marketplace.get("plugins", [])):
            assert plugin["name"] == entry["name"], (
                f"plugin.json name ({plugin['name']}) != "
                f"marketplace.json plugins[{i}].name ({entry['name']})"
            )

    def test_mcp_server_key_matches_plugin_name(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        mcp = _read_json(".mcp.json")

        servers = mcp.get("mcpServers", {})
        assert plugin["name"] in servers, (
            f"MCP server key should be '{plugin['name']}' but .mcp.json has keys: "
            f"{list(servers.keys())}"
        )


# ---------------------------------------------------------------------------
# 6. Repository URL consistency
# ---------------------------------------------------------------------------


class TestRepositoryUrlConsistency:
    """
    Repository URLs in plugin.json and marketplace.json must point to
    the same repo. This is a known violation: plugin.json says
    dirkenglund/vvuq-mcp while marketplace.json says
    dirkenglund/vvuq4ai-plugin.
    """

    def test_repository_urls_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_repo = plugin.get("repository", "")
        # marketplace may have repo at top level or in plugins[] entries
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_repo = entry.get("repository", "")
            if plugin_repo and entry_repo:
                assert plugin_repo == entry_repo, (
                    f"REPOSITORY URL MISMATCH: "
                    f"plugin.json repository ({plugin_repo}) != "
                    f"marketplace.json plugins[{i}].repository ({entry_repo}). "
                    f"These must point to the same GitHub repo."
                )


# ---------------------------------------------------------------------------
# 7. MCP server configuration
# ---------------------------------------------------------------------------


class TestMcpServerConfig:
    """Validate .mcp.json structure and endpoint."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.data = _read_json(".mcp.json")

    def test_mcp_servers_key_exists(self):
        assert "mcpServers" in self.data, ".mcp.json missing 'mcpServers' key"

    def test_at_least_one_server_defined(self):
        servers = self.data.get("mcpServers", {})
        assert len(servers) > 0, ".mcp.json has no MCP servers defined"

    def test_each_server_has_url(self):
        for name, config in self.data.get("mcpServers", {}).items():
            assert "url" in config, (
                f"MCP server '{name}' in .mcp.json is missing 'url' field"
            )

    def test_server_url_is_https(self):
        for name, config in self.data.get("mcpServers", {}).items():
            url = config.get("url", "")
            assert url.startswith("https://"), (
                f"MCP server '{name}' URL must use HTTPS, got: {url}"
            )

    def test_server_url_has_trailing_slash(self):
        """
        The VVUQ MCP SSE endpoint requires a trailing slash.
        This is documented in the project memory and is a known gotcha.
        """
        for name, config in self.data.get("mcpServers", {}).items():
            url = config.get("url", "")
            assert url.endswith("/"), (
                f"MCP server '{name}' URL must end with trailing slash "
                f"(SSE endpoint requires it), got: {url}"
            )


# ---------------------------------------------------------------------------
# 8. Command frontmatter completeness
# ---------------------------------------------------------------------------


class TestCommandFrontmatter:
    """commands/verify.md must have all required frontmatter fields."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.text = _read_text("commands/verify.md")
        self.fm = _parse_frontmatter(self.text)

    def test_has_frontmatter(self):
        assert len(self.fm) > 0, "commands/verify.md has no frontmatter"

    def test_has_name(self):
        assert "name" in self.fm, "commands/verify.md frontmatter missing 'name'"

    def test_has_description(self):
        assert "description" in self.fm, (
            "commands/verify.md frontmatter missing 'description'"
        )

    def test_has_argument_hint(self):
        assert "argument-hint" in self.fm, (
            "commands/verify.md frontmatter missing 'argument-hint'"
        )

    def test_command_name_is_simple_slug(self):
        name = self.fm.get("name", "")
        assert re.fullmatch(r"[a-z][a-z0-9-]*", name), (
            f"Command name '{name}' is not a valid slug (lowercase, alphanumeric, hyphens)"
        )


# ---------------------------------------------------------------------------
# 9. Agent frontmatter completeness
# ---------------------------------------------------------------------------


class TestAgentFrontmatter:
    """agents/vvuq-verifier.md must have all required frontmatter fields."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.text = _read_text("agents/vvuq-verifier.md")
        self.fm = _parse_frontmatter(self.text)

    def test_has_frontmatter(self):
        assert len(self.fm) > 0, "agents/vvuq-verifier.md has no frontmatter"

    def test_has_name(self):
        assert "name" in self.fm, "agents/vvuq-verifier.md frontmatter missing 'name'"

    def test_has_description(self):
        assert "description" in self.fm, (
            "agents/vvuq-verifier.md frontmatter missing 'description'"
        )

    def test_name_matches_filename(self):
        """Agent name in frontmatter should match the filename (without .md)."""
        name = self.fm.get("name", "")
        filename_stem = Path("agents/vvuq-verifier.md").stem
        assert name == filename_stem, (
            f"Agent frontmatter name '{name}' does not match filename stem "
            f"'{filename_stem}'"
        )


# ---------------------------------------------------------------------------
# 10. Skill frontmatter completeness
# ---------------------------------------------------------------------------


class TestSkillFrontmatter:
    """skills/verify-claim/SKILL.md must have all required frontmatter fields."""

    @pytest.fixture(autouse=True)
    def load(self):
        self.text = _read_text("skills/verify-claim/SKILL.md")
        self.fm = _parse_frontmatter(self.text)

    def test_has_frontmatter(self):
        assert len(self.fm) > 0, "SKILL.md has no frontmatter"

    def test_has_name(self):
        assert "name" in self.fm, "SKILL.md frontmatter missing 'name'"

    def test_has_description(self):
        assert "description" in self.fm, "SKILL.md frontmatter missing 'description'"

    def test_has_version(self):
        assert "version" in self.fm, "SKILL.md frontmatter missing 'version'"

    def test_skill_name_matches_directory(self):
        """Skill name in frontmatter should match the directory name."""
        name = self.fm.get("name", "")
        dir_name = "verify-claim"
        assert name == dir_name, (
            f"Skill frontmatter name '{name}' does not match directory "
            f"name '{dir_name}'"
        )


# ---------------------------------------------------------------------------
# 11. MCP tool references are consistent
# ---------------------------------------------------------------------------


class TestMcpToolReferences:
    """
    All tool names referenced in commands, agents, and skills must be
    consistent (same tool names everywhere).
    """

    TOOL_PATTERN = re.compile(r"`(vvuq_\w+)`")

    def _extract_tool_refs(self, relpath: str) -> set[str]:
        text = _read_text(relpath)
        return set(self.TOOL_PATTERN.findall(text))

    def test_command_references_vvuq_resolve(self):
        tools = self._extract_tool_refs("commands/verify.md")
        assert "vvuq_resolve" in tools, (
            f"commands/verify.md should reference vvuq_resolve tool. "
            f"Found references: {tools}"
        )

    def test_agent_references_vvuq_resolve(self):
        tools = self._extract_tool_refs("agents/vvuq-verifier.md")
        assert "vvuq_resolve" in tools, (
            f"agents/vvuq-verifier.md should reference vvuq_resolve tool. "
            f"Found references: {tools}"
        )

    def test_skill_references_vvuq_resolve(self):
        tools = self._extract_tool_refs("skills/verify-claim/SKILL.md")
        assert "vvuq_resolve" in tools, (
            f"skills/verify-claim/SKILL.md should reference vvuq_resolve tool. "
            f"Found references: {tools}"
        )

    def test_all_referenced_tools_are_from_same_set(self):
        """All tool references across all files should use the same tool names."""
        command_tools = self._extract_tool_refs("commands/verify.md")
        agent_tools = self._extract_tool_refs("agents/vvuq-verifier.md")
        skill_tools = self._extract_tool_refs("skills/verify-claim/SKILL.md")

        all_tools = command_tools | agent_tools | skill_tools
        # vvuq_resolve should be referenced everywhere that references tools
        for tools, source in [
            (command_tools, "commands/verify.md"),
            (agent_tools, "agents/vvuq-verifier.md"),
            (skill_tools, "skills/verify-claim/SKILL.md"),
        ]:
            unknown = tools - all_tools
            assert len(unknown) == 0, (
                f"{source} references unknown tools: {unknown}"
            )

    def test_agent_extra_tools_documented(self):
        """
        Agent references vvuq_query which is not mentioned in the command or skill.
        This is acceptable (agent is more capable) but the tool must be real.
        """
        agent_tools = self._extract_tool_refs("agents/vvuq-verifier.md")
        command_tools = self._extract_tool_refs("commands/verify.md")
        skill_tools = self._extract_tool_refs("skills/verify-claim/SKILL.md")

        agent_only = agent_tools - command_tools - skill_tools
        # Document what the agent exclusively references
        # This is informational -- the test passes but logs the difference
        if agent_only:
            # These tools are only referenced in the agent, not in command/skill.
            # This is fine architecturally but worth noting.
            pass
        # The real check: vvuq_query is referenced in the agent
        assert "vvuq_query" in agent_tools, (
            "Agent should reference vvuq_query for detailed topic lookups"
        )


# ---------------------------------------------------------------------------
# 12. Description consistency
# ---------------------------------------------------------------------------


class TestDescriptionConsistency:
    """Descriptions across files should be compatible (not contradictory)."""

    def test_plugin_and_marketplace_descriptions_compatible(self):
        """
        The core meaning should match even if the exact text differs.
        At minimum, if one has a prefix like 'VVUQ4AI -- ' the other
        should either have the same prefix or the non-prefixed version.
        """
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_desc = plugin["description"]
        market_desc = marketplace["metadata"]["description"]

        # These should be identical (they currently are)
        assert plugin_desc == market_desc, (
            f"plugin.json description and marketplace.json metadata.description "
            f"should be identical.\n"
            f"  plugin.json:      {plugin_desc!r}\n"
            f"  marketplace.json: {market_desc!r}"
        )

    def test_marketplace_plugin_entry_description_is_subset(self):
        """
        marketplace.json plugins[].description may be a shorter version
        but should not contradict the main description.
        """
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_desc = plugin["description"]
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_desc = entry.get("description", "")
            # The entry description should be contained within the full
            # description, or they should share key terms.
            key_terms = ["verify", "STEM", "claims"]
            for term in key_terms:
                assert term.lower() in entry_desc.lower(), (
                    f"marketplace.json plugins[{i}].description missing "
                    f"key term '{term}': {entry_desc!r}"
                )


# ---------------------------------------------------------------------------
# 13. License consistency
# ---------------------------------------------------------------------------


class TestLicenseConsistency:
    """License field in JSON files should match the LICENSE file."""

    def test_plugin_json_license_matches_license_file(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        license_text = _read_text("LICENSE")

        plugin_license = plugin.get("license", "")
        # The LICENSE file should contain the license type mentioned in plugin.json
        assert plugin_license.upper() in license_text.upper(), (
            f"plugin.json license is '{plugin_license}' but LICENSE file "
            f"does not contain that string"
        )

    def test_marketplace_plugin_license_matches(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        for i, entry in enumerate(marketplace.get("plugins", [])):
            if "license" in entry:
                assert entry["license"] == plugin["license"], (
                    f"marketplace.json plugins[{i}].license ({entry['license']}) != "
                    f"plugin.json license ({plugin['license']})"
                )


# ---------------------------------------------------------------------------
# 14. No dead file references
# ---------------------------------------------------------------------------


class TestNoDeadFileReferences:
    """
    References to local files (like ./.mcp.json or ./) must resolve to
    actual paths within the plugin directory.
    """

    def test_plugin_json_mcp_servers_path_resolves(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        mcp_path = plugin.get("mcpServers", "")
        resolved = (PLUGIN_ROOT / mcp_path).resolve()
        assert resolved.exists(), (
            f"plugin.json mcpServers path '{mcp_path}' does not resolve to a file: "
            f"{resolved}"
        )

    def test_marketplace_plugin_source_path_resolves(self):
        marketplace = _read_json(".claude-plugin/marketplace.json")
        for i, entry in enumerate(marketplace.get("plugins", [])):
            source = entry.get("source", "")
            resolved = (PLUGIN_ROOT / source).resolve()
            assert resolved.exists(), (
                f"marketplace.json plugins[{i}].source '{source}' does not resolve: "
                f"{resolved}"
            )

    def test_hooks_directory_not_empty_if_present(self):
        """
        If a hooks/ directory exists, it should contain actual hook scripts.
        An empty hooks directory is misleading.
        """
        hooks_dir = PLUGIN_ROOT / "hooks"
        if hooks_dir.is_dir():
            scripts_dir = hooks_dir / "scripts"
            if scripts_dir.is_dir():
                scripts = list(scripts_dir.iterdir())
                # Filter out hidden files like .DS_Store
                scripts = [s for s in scripts if not s.name.startswith(".")]
                assert len(scripts) > 0, (
                    "hooks/scripts/ directory exists but is empty. "
                    "Either add hook scripts or remove the directory."
                )


# ---------------------------------------------------------------------------
# 15. Keywords consistency
# ---------------------------------------------------------------------------


class TestKeywordsConsistency:
    """Keywords in plugin.json and marketplace.json should be consistent."""

    def test_keywords_match(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_kw = set(plugin.get("keywords", []))
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_kw = set(entry.get("keywords", []))
            if entry_kw:
                assert plugin_kw == entry_kw, (
                    f"Keywords mismatch between plugin.json and "
                    f"marketplace.json plugins[{i}].\n"
                    f"  plugin.json:      {sorted(plugin_kw)}\n"
                    f"  marketplace.json: {sorted(entry_kw)}"
                )


# ---------------------------------------------------------------------------
# 16. Author/owner consistency
# ---------------------------------------------------------------------------


class TestAuthorConsistency:
    """Author info in plugin.json should match owner in marketplace.json."""

    def test_author_name_matches_owner(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_author = plugin.get("author", {}).get("name", "")
        market_owner = marketplace.get("owner", {}).get("name", "")

        assert plugin_author == market_owner, (
            f"plugin.json author.name ({plugin_author!r}) != "
            f"marketplace.json owner.name ({market_owner!r})"
        )

    def test_author_email_matches_owner(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_email = plugin.get("author", {}).get("email", "")
        market_email = marketplace.get("owner", {}).get("email", "")

        assert plugin_email == market_email, (
            f"plugin.json author.email ({plugin_email!r}) != "
            f"marketplace.json owner.email ({market_email!r})"
        )


# ---------------------------------------------------------------------------
# 17. Homepage consistency
# ---------------------------------------------------------------------------


class TestHomepageConsistency:
    """Homepage URL should be consistent across files."""

    def test_homepage_matches(self):
        plugin = _read_json(".claude-plugin/plugin.json")
        marketplace = _read_json(".claude-plugin/marketplace.json")

        plugin_hp = plugin.get("homepage", "")
        for i, entry in enumerate(marketplace.get("plugins", [])):
            entry_hp = entry.get("homepage", "")
            if plugin_hp and entry_hp:
                assert plugin_hp == entry_hp, (
                    f"plugin.json homepage ({plugin_hp}) != "
                    f"marketplace.json plugins[{i}].homepage ({entry_hp})"
                )


# ---------------------------------------------------------------------------
# 18. MCP endpoint in README matches .mcp.json
# ---------------------------------------------------------------------------


class TestReadmeEndpointConsistency:
    """README.md should reference the same MCP endpoint as .mcp.json."""

    def test_readme_mentions_mcp_url(self):
        mcp = _read_json(".mcp.json")
        readme = _read_text("README.md")

        for name, config in mcp.get("mcpServers", {}).items():
            url = config.get("url", "")
            assert url in readme, (
                f"README.md does not mention MCP server URL '{url}' "
                f"(server: {name})"
            )


# ---------------------------------------------------------------------------
# 19. No placeholder/TODO content in shipped files
# ---------------------------------------------------------------------------


class TestNoPlaceholderContent:
    """Shipped plugin files should not contain TODO, FIXME, or placeholder text."""

    FILES_TO_CHECK = [
        ".claude-plugin/plugin.json",
        ".claude-plugin/marketplace.json",
        ".mcp.json",
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
        "README.md",
    ]

    PLACEHOLDER_PATTERNS = [
        re.compile(r"\bTODO\b", re.IGNORECASE),
        re.compile(r"\bFIXME\b", re.IGNORECASE),
        re.compile(r"\bHACK\b", re.IGNORECASE),
        re.compile(r"\bXXX\b"),
        re.compile(r"<your[- ].*>", re.IGNORECASE),
        re.compile(r"example\.com"),
        re.compile(r"placeholder", re.IGNORECASE),
    ]

    @pytest.mark.parametrize("relpath", FILES_TO_CHECK)
    def test_no_placeholders(self, relpath: str):
        text = _read_text(relpath)
        for pattern in self.PLACEHOLDER_PATTERNS:
            matches = pattern.findall(text)
            assert len(matches) == 0, (
                f"{relpath} contains placeholder text matching "
                f"'{pattern.pattern}': {matches}"
            )


# ---------------------------------------------------------------------------
# 20. JSON files are valid JSON
# ---------------------------------------------------------------------------


class TestJsonValidity:
    """All JSON files must be parseable."""

    JSON_FILES = [
        ".claude-plugin/plugin.json",
        ".claude-plugin/marketplace.json",
        ".mcp.json",
    ]

    @pytest.mark.parametrize("relpath", JSON_FILES)
    def test_valid_json(self, relpath: str):
        p = PLUGIN_ROOT / relpath
        text = p.read_text()
        try:
            json.loads(text)
        except json.JSONDecodeError as e:
            pytest.fail(f"{relpath} is not valid JSON: {e}")


# ---------------------------------------------------------------------------
# 21. Frontmatter delimiter correctness
# ---------------------------------------------------------------------------


class TestFrontmatterDelimiters:
    """Markdown files with frontmatter must have proper --- delimiters."""

    MARKDOWN_FILES = [
        "commands/verify.md",
        "agents/vvuq-verifier.md",
        "skills/verify-claim/SKILL.md",
    ]

    @pytest.mark.parametrize("relpath", MARKDOWN_FILES)
    def test_frontmatter_has_opening_and_closing_delimiters(self, relpath: str):
        text = _read_text(relpath)
        lines = text.split("\n")
        assert lines[0].strip() == "---", (
            f"{relpath} does not start with '---' frontmatter delimiter"
        )
        # Find closing delimiter (must be after line 0)
        closing_found = False
        for line in lines[1:]:
            if line.strip() == "---":
                closing_found = True
                break
        assert closing_found, (
            f"{relpath} is missing closing '---' frontmatter delimiter"
        )
